### ISSUE TITLE
query for reset button

### ISSUE THREAD

**Issue by agriii927** [VolkovLabs/volkovlabs-form-panel#100]
Hello! Can you add an option to attach query to reset button?
My case is: I have Data manipulation widget table with parameters, by clicking on Submit button with POST query I connect to REST API with values of all parameters and get the prediction of ML model. 
What I want to add: add a query/ area for it for clicking reset button. If I had it,  I can refresh my parameters data from database (only when I want it, by clicking the button).

I tried to use this query as initial one but my data manipulation panel always refreshes even I don't want it. For instance, It is refreshed after clicking submit button, but I don't want such behavior from it.

**Comment by mikhail-vl** [comment]
@agriii927 Thank you for submitting the feature.

  I will look into it and will get back to you if I have any questions.

**Comment by mikhail-vl** [comment]
Custom Code added to the Reset button in upcoming release 3.1.0.
