### ISSUE TITLE
how to update other fields (onOptionsChange usage)

### ISSUE THREAD

**Issue by lynhnn** [VolkovLabs/volkovlabs-form-panel#101]
Hi,
I use my own scripts for both initial request and update request. However, I don't know how to update other elements once I select a dropdown element. My use case is that I loaded a list of items. And once I select an item, the rest of the form should load that item properties so I can edit them. However, I still don't know how to call to update the other elements. Is there a hook to listen to the selected element like onChange? or anything like that?

**Comment by mikhail-vl** [comment]
Hello @lynhnn,

  This is how we define SELECT elements. It has predefined onChange event, which updates selected value in Options.
```
            {element.type === FormElementType.SELECT && (
              <InlineField
                label={element.title}
                grow={!!!element.width}
                labelWidth={element.labelWidth}
                tooltip={element.tooltip}
                transparent={!!!element.title}
              >
                <Select
                  value={element.value}
                  onChange={(event: SelectableValue) => {
                    element.value = event?.value;
                    onOptionsChange(options);
                  }}
                  width={element.width}
                  options={element.options || []}
                  className={highlightClass(element)}
                />
              </InlineField>
            )}
```
  
  Do you want to have you own custom onChange function? Will it help you?

**Comment by ftasso** [comment]
Hello,
I'm using this very interesting plugin!
Also my use case needs a custom onChange for a SELECT field, I would really appreciate an example.

Thank you,
Fabrizio

**Comment by parumsancto** [comment]
It will be very helpful. Please do it.

> @ftasso, Thank you, I will look into custom `onChange` events.
> 
> I am thinking of implementing a Custom Code for the `onOptionsChange` event, which will allow to create dynamic forms.

**Comment by mikhail-vl** [comment]
We implemented various JavaScript hooks and refactoring element states in v3.

**Comment by imReker** [comment]
> We implemented various JavaScript hooks and refactoring element states in v3.

Any example for this? I checked the commits and didn't find anything related to this use case. Currently onchange is a function to change element, rather than a event trigger which will be called on element's value has changed.
