### ISSUE TITLE
URL for Submit Button

### ISSUE THREAD

**Issue by SairajSawant288** [VolkovLabs/volkovlabs-form-panel#102]
Hi @mikhail-vl,

How can I assign a URL to a button which will navigate to another dashboard instead of the default API endpoints? 

The URL assigned to the button contains dashboard parameters that are used for the initial GET request in the navigated dashboard.

Thank you.

**Comment by mikhail-vl** [comment]
The Custom Code for the Reset button was added in v3.1.0.
