### ISSUE TITLE
Show/hide element

### ISSUE THREAD

**Issue by ftasso** [VolkovLabs/volkovlabs-form-panel#103]
Hello,
my panel have a main select and a lot of fields, each select option needs a specific subset of fields and not all.
Is it possible to show/hide programmatically a specific element in order to simplify the user navigation?

Thank you,
Fabrizio

**Comment by ftasso** [comment]
Hello Mikhail,
thank you for your enthusiasm.

I have an idea about a different use of your plugin.
Grafana is a powerful software but have a BIG limitation, the template variables are not groupable in a specific GUI like a command panel.  Morover if you have more panels, charts table etc, and each of these panels use a specific variable or a subset of variables, it's very difficult for the final user to understand the panel dynamic.
Your plugin already do this with a few operations, I wrote a basic guide for the other users.
Please take a look at the attached files, I have also a suggestion to improve the plugin.

[VolkovLabs.pdf](https://github.com/VolkovLabs/volkovlabs-form-panel/files/9829885/VolkovLabs.pdf)
[VolkovLabs - changes.pdf](https://github.com/VolkovLabs/volkovlabs-form-panel/files/9829888/VolkovLabs.-.changes.pdf)
[VolkovLabs_TEST_dashboard.txt](https://github.com/VolkovLabs/volkovlabs-form-panel/files/9829894/VolkovLabs_TEST_dashboard.txt)

Thank you,
Fabrizio

**Comment by mikhail-vl** [comment]
@ftasso, this is awesome.

  I will take a look and get back to you shortly.

**Comment by mikhail-vl** [comment]
We implemented various JavaScript hooks and refactored element states in v3.
Version 3.1.0 introduced conditional element visibility.
