### ISSUE TITLE
Doubt about query synchronization

### ISSUE THREAD

**Issue by ftasso** [VolkovLabs/volkovlabs-form-panel#104]
Hello,
I have a doubt about the query synchronization, please take a look a this sequences:

after panel loading (at the begin) I have this sequence:
- query execution having a template variable of Grafana, for example $varOne, and a correct syncronization with the query termination
- call to Init custom code and "data.series" correctly filled

changing $varOne I have this sequence:
- query execution without synchronization with the termination
- immediately call to Init custom code and "data.series" with the previous (initial) values

I'm using Grafana 9.2.1

I would really appreciate a clarification about the load/refresh dynamic.

Thank you,
Fabrizio

**Comment by mikhail-vl** [comment]
@ftasso Thank you for opening the issue.

  That's an interesting question and I will need to reproduce it. I don't quite get "query execution without synchronization with the termination" what it means and need to look at it.

  Grafana should take care of refreshing panel when query changes. Panel subscribed to Refresh events.
  Have you tried using the previous version 9.1.X?

**Comment by ftasso** [comment]
Hello,

"Have you tried using the previous version 9.1.X?" Done, problem still remains.

I made a simple dashboard for debug this problem, it use a Mysql database but no tables are needed.
Dashboard have 2 queries, the first is used to populate an option select (tags) and the second is used to retrieve a new value according to the option selected.
Changing "tags" option value (then apply button) starts a Grafana variable change, this variable is used in the second query. 
Init (custom code) is correctly called but the dataSeries I have is everything the same, no fresh data are loaded.
Please take a look, 

[grafana2.txt](https://github.com/VolkovLabs/volkovlabs-form-panel/files/9868724/grafana2.txt)

Bye

**Comment by ftasso** [comment]
Morning,
news about this issue? Did you look my test dashboard?

Thank you for you support.

Fabrizio

**Comment by mikhail-vl** [comment]
We implemented various JavaScript hooks and refactored element states in v3.
Using Data Sources for Initial and Update requests introduced in v3.1.0.
