### ISSUE TITLE
Text of the inscriptions

### ISSUE THREAD

**Issue by parumsancto** [VolkovLabs/volkovlabs-form-panel#110]
How to customize the inscriptions (like "Please confirm to update changed values?") in the confirmation window (button names)?
This is useful to localize the interface to other languages (not English).

**Comment by mikhail-vl** [comment]
@parumsancto Thank you for opening the issue. It's a great feature.

  Grafana is still working on support Internationalization and I have to check if it's support for the plugins at all.
  Meanwhile, we may define panel options to update all inscriptions.

  What language you are looking for?

**Comment by parumsancto** [comment]
@mikhail-vl 
>What language you are looking for?
Ukrainian
