### ISSUE TITLE
Consider adding a "getUpdatedValues()" function to determine changed form values

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#112]
Consider adding a function called something like "getUpdatedValues()" that returns a container of the update values in the form {'id1':'newValue1', 'id2':'newValue2', ...}. This would basically match the table you build for the confirmation dialog. It would help to optimize when building the "Update Request".  Currently you must send all form elements in the update when only a select few have changed. I don't believe there is any other way to determine what has changed in the form. 

-Ray

**Comment by mikhail-vl** [comment]
@rantinray I am working on a feature toggle to send only updated values. Will it work for you?

**Comment by mikhail-vl** [comment]
@rantinray Looking at the issue closer, we identified that `json` with parsed values from the Initial Request are not exposed in the Update Request.

  #117 fixes the issue and will be a part of the upcoming release. Instructions also updated in README: https://github.com/VolkovLabs/volkovlabs-form-panel#update-request

  Meanwhile, you can download the plugin with latest updated from GitHub Action to test: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/3424937351

  Please let us know if there is anything else.

**Comment by rantinray** [comment]
@mikhail-vl I am on travel this week, but I will try to find time to test your updates.  I reviewed the README and it looks like it will do what I need.  I will let you know if I run into any difficulties.

Thanks again for your prompt respone.

-Ray

**Comment by mikhail-vl** [comment]
@rantinray Please keep us updated and let us know if there is anything else.

**Comment by rantinray** [comment]
@mikhail-vl I was able to test this new feature by loading the 2.7.0 zip file you referenced.  It worked fine for me.

Thanks,
-Ray

**Comment by mikhail-vl** [comment]
@rantinray Thank you for confirming.

  I am finishing Code Editor Suggestions and will release a new version with all updates in an hour or so.

**Comment by rantinray** [comment]
@mikhail-vl I tried calling the "notifySuccess()" and "notifyError()" methods while testing the version you pointed me to. They did not resolve.  Were they supposed to be in that build? https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/3424937351
 
-Ray

**Comment by mikhail-vl** [comment]
@rantinray Notifications was implemented later and it is not a part of that Action.

  To try the latest updates, download the artifact from the most recent Action: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/workflows/ci.yml

**Comment by mikhail-vl** [comment]
@rantinray Data Manipulation Panel 2.7.0 was released: https://github.com/VolkovLabs/volkovlabs-form-panel/releases/tag/v2.7.0

  Please let us know if you need anything else.
