### ISSUE TITLE
How SAML Authorization can be sent to the backend?

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-form-panel#115]
How SAML Authorization can be sent to the backend?

**Comment by tjbanks** [comment]
Thanks @mikhail-vl! I wonder about authenticating to other backend api services using grafana's authorization token. Eg - SSO (https://www.keycloak.org) using oauth2.

**Comment by hwinkel** [comment]
We're also thinking about the same, If a Grafana user is authenticated, and starts to manipulate data over a REST API this API might have its own RBAC layer. Somehow, the Auth Token should be propagated to the REST API.

Further, how can such Form handle Authentication like READ or WRITE access, i.e. disable editing or show errors messages if a non-authorized user tries to manipulate the data via POST or PUT.

**Comment by paulwer** [comment]
any updates about a possible implementation?

**Comment by mikhail-vl** [comment]
Data Sources for Initial and Update requests were implemented in v3.1.0.
