### ISSUE TITLE
Files upload

### ISSUE THREAD

**Issue by mudasarellahi** [VolkovLabs/volkovlabs-form-panel#122]
Hi,

I have a requirement to submit the Textarea along with user uploaded files. Is there a way to upload files and send to API?

**Comment by mikhail-vl** [comment]
@mudasarellahi We was planning to add this functionality, but no one asked for it so far.

  We will look into implementing it in the upcoming version.

  Do you have requirements for amount of files, their sizes and formats?

**Comment by vanimesh** [comment]
When can we expect this feature to be onboarded ?

**Comment by mikhail-vl** [comment]
@vanimesh I was planning to close most of the issue for Data Manipulation panel in July/August.

  We got behind with required refactoring, which was completed in 3.0.0.

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe This feature request is schedule for the upcoming release.
