### ISSUE TITLE
The provided "server-pg" (API server) scripts or Grafana plugin don't work as expected

### ISSUE THREAD

**Issue by maleksan** [VolkovLabs/volkovlabs-form-panel#124]
The provided "server-pg" (API server) scripts or Grafana plugin don't work as expected.

Grafana version: v9.2.2
volkovlabs-form-panel version: v2.7.0
Postgresql version: v14.5.0
The "server-pg" (API server) scripts are from: 
https://github.com/VolkovLabs/volkovlabs-form-panel/tree/main/server-pg

"server-pg" (API server) successfully up and running, on publicly available server, so it is possible to connect to the API Server directly:

```bash
[INFO wait] --------------------------------------------------------
[INFO wait] docker-compose-wait 2.9.0
[INFO wait] ---------------------------
[DEBUG wait] Starting with configuration:
[DEBUG wait] - Hosts to be waiting for: []
[DEBUG wait] - Paths to be waiting for: []
[DEBUG wait] - Timeout before failure: 30 seconds
[DEBUG wait] - TCP connection timeout before retry: 5 seconds
[DEBUG wait] - Sleeping time before checking for hosts/paths availability: 0 seconds
[DEBUG wait] - Sleeping time once all hosts/paths are available: 0 seconds
[DEBUG wait] - Sleeping time between retries: 1 seconds
[DEBUG wait] --------------------------------------------------------
[INFO wait] docker-compose-wait - Everything's fine, the application can now start!
[INFO wait] --------------------------------------------------------
Server for Postgres is running on port 3001...
```

The API server is accessible from the local machine and Grafana instance:

```bash
nc -zv <api_server_ip> 3001
<api_server_ip> (<api_server_ip>:3001) open
```

Created necessary db table by porvided sql script:
https://github.com/VolkovLabs/volkovlabs-form-panel/blob/main/server-pg/feedback.sql

Configured the Data Manipulation plugin:
![2022-12-08 182358](https://user-images.githubusercontent.com/73186636/206512682-ac145d92-1d43-4cda-ba3e-4f1c6ae7def8.png)
![image](https://user-images.githubusercontent.com/73186636/206513421-0d67a2e5-ceea-492d-8ed4-e1f47aaadea7.png)

Submit and there is such error:
```
Request
TypeError: Cannot read properties of undefined (reading 'status')
```
![2022-12-08 182113](https://user-images.githubusercontent.com/73186636/206512892-1c125188-f20c-48f0-a5fe-40c40f7978aa.png)

In the API server log file no any new records. The database also has no new records.

Tried to change in Update Request section Content-Type from Application/json to Text/plain, the same - no success.

What's wrong here?

**Comment by mikhail-vl** [comment]
@maleksan Do you see the request in the Browser's Inspect -> Network traffic (Chrome)?
You should be able to see the request and response from the API Server.

**Comment by maleksan** [comment]
I made modification in `server.ts` script, by adding url for feedbacks section, like this:
```javascript
///
      /**
       * Update the database
       */
      // q1 feedbacks
      if (req.url === '/q1') {
        await client.query(
          'INSERT INTO feedbacks(created, name, email, description, type) VALUES(NOW(), $1, $2, $3, $4)',
          [values['name'], values['email'], values['description'], values['type']]
        );
      }
    });
///
```

Now in Chrome Network q1 request is with {blocked:mixed-content} status:
![image](https://user-images.githubusercontent.com/73186636/206545714-9ed9f500-effb-4e9d-93d3-e15855006a9d.png)

**Comment by mikhail-vl** [comment]
@maleksan The best strategy to avoid mixed content blocking is to serve all the content as HTTPS instead of HTTP: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

  Check the protocol used to connect to Grafana and API. It should be the same.

  Here is the article where we explained how to use NGINX and HTTP Proxy as alternatives: https://volkovlabs.com/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904

**Comment by maleksan** [comment]
> @maleksan The best strategy to avoid mixed content blocking is to serve all the content as HTTPS instead of HTTP: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
> 
> Check the protocol used to connect to Grafana and API. It should be the same.
> 
> Here is the article where we explained how to use NGINX and HTTP Proxy as alternatives: https://volkovlabs.com/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904

You are right, indeed the problem is that different protocols are used, Grafana https and api http.
A quick workaround could be "Enabling mixed content in Google Chrome", e.g., https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html?lang=en

Tested this method and it works.
In the long term, of course, the api should be switched to the https protocol as Grafana.
I think this issue can be closed then.
Thank you very much for your prompt help.

**Comment by maleksan** [comment]
If you don't mind I have another question.
As for this script part:
```javascript
  /**
   * GET
   */
  if (req.method === 'GET') {
    /**
     * Get values from database
     */
    const query = await client.query('select * from feedbacks where name=$1;', [req.url.replace('/', '')]);
    const values = query.rows[0];

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.write(JSON.stringify(values));
    res.end();

    console.log('Requested', values);

    return;
  }
```

Now trying to get data from Postgres like thisЖ

But API server docker container is failing and restarts with this error:
![image](https://user-images.githubusercontent.com/73186636/206553713-9aef4078-c3e1-4720-9a77-ba93131692b2.png)

```bash
node:internal/errors:484
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
at new NodeError (node:internal/errors:393:5)
at write_ (node:_http_outgoing:843:11)
at ServerResponse.write (node:_http_outgoing:808:15)
at Server.<anonymous> (/app/server.ts:49:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v19.2.0
```

What am I doing wrong here?

**Comment by mikhail-vl** [comment]
@maleksan Looks like your SQL query returned `undefined`, which means that no data was found.

  You can't write `undefined` to the request:

```
res.write(JSON.stringify(values));
```

**Comment by maleksan** [comment]
According with your original sql query `select * from feedbacks where name=$1;`
I can get data from this query `select * from feedbacks where name='User'` directly in Postgres:
![image](https://user-images.githubusercontent.com/73186636/206557670-2c5125b3-cb65-4c5c-a5c9-436a143d6b4c.png)

**Comment by mikhail-vl** [comment]
@maleksan Glad, it worked out.

  Thank you for submitting the PR. I will review and share it with the community shortly.
