### ISSUE TITLE
Create a configuration option to only call the Initial Request on dashboard load?

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#126]
Is it possible to configure the Data Manipulation panel to only call the Initial Request on dashboard load?  I have this panel on a dashboard that has other panels that require regular updates and I have an auto refresh interval set.  Right now the Initial Request gets called at every refresh.  The problem with this is that if the user is changing values on the Data Manipulation panel, they all get reset based on the Initial Request being called every refresh cycle.

If this is not already configurable, could you consider adding this as a configuration option? Sort of like the drop down when configuring a dashboard query variable.  Something like:

    Initial Request Refresh: "On dashboard load"/"default"

I am not actually sure what the default should be called or how you would describe it. 

Thanks
-Ray

**Comment by 0xyei** [comment]
You can probably fix this by using a global variable on dashboard. Create a new variable called "dload" and set the initial value to none, then on the code for loading of plugin check if the variable has value as "none", if yes, do the request and then change the variable to I don't know, whatever.

Next time the refresh hits, since the variable is not "none" anymore, the request will not be executed.

Thanks

**Comment by asimonok** [comment]
@rantinray Thanks for the request.

You can use custom code for making initial requests and update elements to prevent rewriting of element values after dashboard refresh.

Example of custom code for initial request:
```
const getValues = async () => {
  const isFirstLoad = elements.every((element) => !element.value) // check if all values are empty;
  
  if (isFirstLoad) {
    const response = await fetch(); // get some data
    const json = await response.json();
    
   // update initial element values
   onChange(elements.map((element) => ({
     ...element,
     value: json[element.id],
   }))
  }
}

return getValues();
```

Please let us know if it works for you

**Comment by mikhail-vl** [comment]
@asimonok Thank you.

  Documentation updated: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/
