### ISSUE TITLE
Option for DELETE request

### ISSUE THREAD

**Issue by marko-savic** [VolkovLabs/volkovlabs-form-panel#127]
Hi, great plugin and so far I found it very useful.

I just wanted to ask, how should delete be done?
Will be support for the DELETE request?

**Comment by mikhail-vl** [comment]
@marko-savic Thank you for opening feature request.

  DELETE option added and will be a part of the upcoming release tentatively this weekend.
  Meanwhile, you can download artifact from the CI workflow: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/workflows/ci.yml
