### ISSUE TITLE
How to Reset or go back to the initial state after submitting. 

### ISSUE THREAD

**Issue by Yoslandy** [VolkovLabs/volkovlabs-form-panel#136]
Hi,
I don't think this is an issue, but I can't find the way to get it done.

In my project, I'm saving and loading the data successfully so far. The documentation helps me a lot, even though there was not very detailed at some points. However, I love this plugin.

The point is, when I'm using the dropdown (Select with Custom Options), I got to fill it with data, but at the time to reset it, or select one specific item from code, there is my problem, didn't find how. I didn't reach to the "Radio Group with Custom Options" yet, but I think I will reach to the same point.

For instance: I'm using the Select to load some names and delete them at convenience. When I delete the item, I even refresh the list in the Select, **but I would like to show "Choose" again like in the beginning or have the possibility of select any item I want**. (Probably the same will happen with Radio Group, to go back to the initial state)

I'm pretty sure this is possible already, but I don't really know how.

Can someone help me please. 

Thanks in advance.

**Comment by Yoslandy** [comment]
I found a way that helps me enough. This will always show the first element of the array.

as example:
newOptionsArray = {
     value: "Id of my item",
     label: "name of my item"
}
options.elements[0].options = newOptionsArray
options.elements[0].value = newOptionsArray[0].value
onOptionsChange(options)

I hope the code is clear for who need it. If not, just let me know.

**Comment by mikhail-vl** [comment]
@Yoslandy Do you have initial GET Request? Then you can use `initialRequest()` like explained in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/code#perform-initial-request-after-update-request-or-show-error

  If you don't have initial request, then your example will work.

**Comment by mikhail-vl** [comment]
@Yoslandy Do you use this code in the Update or Initial Request?

```javascript
newOptionsArray = {
  value: "Id of my item",
  label: "name of my item"
}

options.elements[0].options = newOptionsArray
options.elements[0].value = newOptionsArray[0].value
onOptionsChange(options)
```

**Comment by mikhail-vl** [comment]
> The documentation helps me a lot, even though there was not very detailed at some points. However, I love this plugin.

  Let us know when and what is not clear and we will update it. You are welcome to submit PR as well: https://github.com/VolkovLabs/volkovlabs.io/tree/main/docs

**Comment by Yoslandy** [comment]
WOW!, Thanks @mikhail-vl 

There was the secret that I didn't see, using initialRequest() in the Update call to reset everything like in the initial request.

Great!!

I was using it in both Request, now only in the initial request.

Just an advice if you allow me, just to improve the plugin. 
Some Select or Dropdowns allow you to assign to it -1 to go back to the "Choose option". I was looking for it and try it like that but don't get through. So, with the code above I go back to the first position of the array, but I find helpful show "Choose" again as an initial value. I hope you understand me.  

But still, great work!

**Comment by mikhail-vl** [comment]
@Yoslandy It makes sense, should be easy to implement.

**Comment by Yoslandy** [comment]
@mikhail-vl Thanks again. Your response is extremely fast. I hope I have helped to improve the plugin, and if there is something else that I can do let me know. I can't wait to see the whole potential of this great tools.

**Comment by mikhail-vl** [comment]
We improved various JavaScript hooks and updated element states in v3.
You can add a custom code in the Reset request instead of using the Initial Request in v3.1.0.
