### ISSUE TITLE
CORS error, body not received in django server

### ISSUE THREAD

**Issue by ascoril** [VolkovLabs/volkovlabs-form-panel#137]
Graphana Custom Code:

/**
 * Set body
 */
const body = {};
options.elements.forEach((element) => {
  if (!options.update.updatedOnly) {
    body[element.id] = element.value;
    return;
  }

  /**
   * Skip not updated elements
   */
  if (element.value === initial[element.id]) {
    return;
  }

  body[element.id] = element.value;
});

/**
 * Set URL
 */
const url = 'http://127.0.0.1:7000/db';
console.log(body)

/**
 * Fetch
 */
const resp = fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(body),
})
  .catch((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });

Django code:

@csrf_exempt
def db(request):
    print('entering db')
    log = open("log.txt", "a+")
    log.write("\n" + str(datetime.now()) + "\t Starting")
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    print(body)

Error in Network tab

![image](https://user-images.githubusercontent.com/11460839/212880485-d6f57d8f-f919-4e49-ace6-7502cd8c8ed1.png)

![image](https://user-images.githubusercontent.com/11460839/212880586-e29674eb-48b9-4239-a880-41e7d65279bf.png)

**Comment by ascoril** [comment]
Any suggestions ?

**Comment by ascoril** [comment]
SOlved it from Django side.

**Comment by mikhail-vl** [comment]
@ascoril Nice, we explained how to deal with CORS in the blog post: https://volkovlabs.io/blog/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904

 We will update the documentation to make it clear.
