### ISSUE TITLE
Only first selection of Radio Group with Custom Options (RGCO) works in multiple RGCO setup

### ISSUE THREAD

**Issue by KieranJanin-BYTP** [VolkovLabs/volkovlabs-form-panel#139]
I'm trying to create a form with multiple options that are all visible. There are several problems:

- Only the first group can be selected as I want
- When selecting any of the other groups, it selects the "First choice" without being able to choose anything else.
- If I go back and change my choice for the first group, all the other groups revert back to "Last choice"

I attached the JSON of the panel to recreate the scenario.
[Multiple RGCO problem.txt](https://github.com/VolkovLabs/volkovlabs-form-panel/files/10465220/Multiple.RGCO.problem.txt)

**Comment by asimonok** [comment]
@KieranJanin-BYTP thanks for the attached json. It helped much.
The problem is that radio group options have the same values - they are empty.
Please use unique values within group for each options and it solves the issue.
```
{
  "label": "First Choice",
  "value": "1"
},
{
  "label": "Choice 2",
  "value": "2"
},
...
{
  "label": "Last Choice",
  "value": "last"
}
```
