### ISSUE TITLE
Is there a detailed guide with real examples?

### ISSUE THREAD

**Issue by nadavran** [VolkovLabs/volkovlabs-form-panel#140]
Hi, 

I would love to test the data manipulation on my Grafana / MySQL setup. I think it is super cool and opens tons of options for the Dashboard use cases. 
I want to follow your recommendation and use NGINX. I'm afraid I'm not technical enough to do this on my own without a detailed example of how to set up everything. So Far I've installed the "Data Manipulation" Plugin and NGINX server. 
I need a detailed guide for the NGINX configuration setup.  Any chance you can make a quick technical video guide demonstrating that? 

thanks, 
Ran.

**Comment by mikhail-vl** [comment]
@nadavran There is a MySQL API example with NGINX configuration added by the community: https://github.com/VolkovLabs/volkovlabs-form-panel/tree/main/server-mysql. There is another example in the `nginx` folder.

  Please take a look and let me know.

  We just finished consolidating documentation and blog on our website, and I plan to improve documentation for NGINX, CORS, and Server for Data Manipulation in the coming week or two.

**Comment by mikhail-vl** [comment]
There are multiple tutorials on our YouTube channel and in the documentation to get started: https://volkovlabs.io/plugins/volkovlabs-form-panel/

**Comment by mikhail-vl** [comment]
Data Sources for Initial and Update requests were added in v3.1.0.
We will post a blog post and YouTube tutorial about the latest features end of August.
