### ISSUE TITLE
How to pass field value as parameter to the POST URL?

### ISSUE THREAD

**Issue by juampa2010** [VolkovLabs/volkovlabs-form-panel#141]
Hi, What am I doing wrongly?

This is the form:
![image](https://user-images.githubusercontent.com/25010316/220661895-53d9f893-8ccd-483f-9c97-8b758f83ec21.png)

Parameter I want to add to the end of the POST url is the actual 'umbral' form value.

If I set 30 as fix value my php works fine and I get the update into MySQL database.
POST is: http://xyz:7080/Arduino/MySQL/FunnyVan-DHT22_ESP8266_Lolin/update_temp.php?umbral=30

If I use something like **${umbral}** it does not work, so probably I am using wrong way to reference the form 'umbral' variable.
POST is: http://xyz:7080/Arduino/MySQL/FunnyVan-DHT22_ESP8266_Lolin/update_temp.php?umbral=${umbral}

Can you help me?
Thanks

**Comment by mikhail-vl** [comment]
@juampa2010 Data Manipulation sends all elements in the payload. If you wish to send an element value in the URL, then use a custom request.

  There is an example in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

  `$var` is used for dashboard variables, which can be used in the URL if defined on the dashboard.
  Let me know if it's clear.

**Comment by mikhail-vl** [comment]
@apellew There is an example in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

  Let me know if there is anything else.

**Comment by juampa2010** [comment]
Yes, it worked for me, many thanks for the support.

**Comment by mikhail-vl** [comment]
@juampa2010 Thank you for confirming.
