### ISSUE TITLE
net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by criticalboot** [VolkovLabs/volkovlabs-form-panel#143]
Hi,
I have installed your MySQL server and built it as docker and Grafana is running in another docker. when I am making a post request I get net::ERR_NAME_NOT_RESOLVED Error. 

I am able to ping the server-msyql from the docker container. I tried this server with 3rd party rest service and it worked as expected.

**Comment by criticalboot** [comment]
nevermind got it worked. changing the docker-name to localhost in the URL field fixed the issue.

**Comment by mikhail-vl** [comment]
@criticalboot Great, it's working for you!

  Let us know if there is anything else.
