### ISSUE TITLE
POST dashboard variable with POST API

### ISSUE THREAD

**Issue by Mitthat** [VolkovLabs/volkovlabs-form-panel#144]
Hi, i am POSTing an API, which requires two fields, one field would be entered by the user and another one i want to configured as the dashboard variable which has been selected. how to post the dashboard variable when my API is posted

**Comment by mikhail-vl** [comment]
@Mitthat Dashboard variables are supported in the payload. You can define a disabled element with a value `$var`.
  The variable should be replaced automatically: https://volkovlabs.io/plugins/volkovlabs-form-panel/variables/

  Another option is to use Custom Update Request and set it in the payload using JavaScript code: https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

  Let me know if it helps.
