### ISSUE TITLE
GraphQL Backend

### ISSUE THREAD

**Issue by hwinkel** [VolkovLabs/volkovlabs-form-panel#148]
Are there any plans for a GrqphQL Backend for Data Manipulation ?

**Comment by mikhail-vl** [comment]
@hwinkel We have multiple API Server implementations which can be adapted for GraphQL backend: https://volkovlabs.io/plugins/volkovlabs-form-panel/#api-servers.

  Please share to add to the documentation and share with the community if you create it.

**Comment by mikhail-vl** [comment]
Using Data Sources for Initial and Update requests introduced in v3.1.0.
You can use or develop a GraphQL backend and interact with it using the Data Manipulation panel.
