### ISSUE TITLE
script for Submit button?

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/volkovlabs-form-panel#150]
I may be wrong. I have not read  all the documents and issues there.
There are methods like Delete,Patch,Post,Put which a user may define all.   When a user clicks the Submit button, what method will it call?  Is it possible to attach script to the Submit button so the user can choose a method (for example based on dashboard variables), do some validation, or even set payload before sending out  restful requests?  For Delete, adding a Delete button may be better. 
I have not done anything yet, but there is my imagination: Define a dashboard variable, like row_id (which can be hidden from the viewer), a regular table which will send its row id to variable row_id when a user clicks a row (for example,  by datalink). Data Manipulation Panel gets that row_id, and will be able to populate its elements’ value (sharing the query result from the regular table).  We can  also add a New button (a user can set row_id =1 in its script  to indicate  a new row).   Then CRUD  is complete. 
  By now, for Delete, we can use Grafana button (like this:https://github.com/speakyourcode/grafana-button-panel), for New, we can use dashboard datalink to implement. but if we combine Delete and New to the Data Manipulation Panel, it will be way better.

**Comment by mikhail-vl** [comment]
@alpglide I would definitely suggest to read documentation and watch YouTube tutorials: https://volkovlabs.io/plugins/volkovlabs-form-panel/

You can create your own Custom Requests as described in https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

Everything from your imagination should be possible. You can use Environment Variables in the URL and also in the Custom Code.

Please let me know if there is anything else.

**Comment by alpglide** [comment]
> https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

@mikhail-vl  That link real helps. thanks.  We can close the ticket now. Your quick is appreciated.

**Comment by mikhail-vl** [comment]
@alpglide Try it out. We just released a new version with the latest updates, which was updated in the Grafana Catalog.
