### ISSUE TITLE
Visualize realtime data through echart using MQTT 

### ISSUE THREAD

**Issue by SRoy0001** [VolkovLabs/volkovlabs-form-panel#151]
Hi, I want to visualize the automobile metrics using Dynamic Data + Time Axis graph of Apache Echart. The data is coming from an MQTT topic 'gps/035538/location'. The datasource is configured in Grafana, but I'm unable to visualize it. This is the code below for the graph. Where do I add the topic name in this code?

`function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
      Math.round(value)
    ]
  };
}

let values = [];
let now = new Date(1997, 9, 3);
let oneDay = 24 * 3600 * 1000;
let value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
  values.push(randomData());
}

option = {
  grid: {
    top: '4%',
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  tooltip: {
    trigger: 'axis',
    formatter: function (params) {
      params = params[0];
      var date = new Date(params.name);
      return (
        date.getDate() +
        '/' +
        (date.getMonth() + 1) +
        '/' +
        date.getFullYear() +
        ' : ' +
        params.value[1]
      );
    },
    axisPointer: {
      animation: false
    }
  },
  xAxis: {
    type: 'time',
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [
    {
      name: 'Fake Data',
      type: 'line',
      showSymbol: false,
      data: values
    }
  ]
};

setInterval(function () {
  for (var i = 0; i < 5; i++) {
    values.shift();
    values.push(randomData());
  }
  echartsInstance.setOption({
    series: [
      {
        data: values
      }
    ]
  });
}, 1000);

return option;`

Any help on this would be much appreciated.

**Comment by mikhail-vl** [comment]
@SRoy0001 It's not a correct repository for Apache ECharts. Please reopen the issue in the https://github.com/volkovlabs/volkovlabs-echarts-panel
