### ISSUE TITLE
Initial response Body already consumed

### ISSUE THREAD

**Issue by joshuakosasih** [VolkovLabs/volkovlabs-form-panel#153]
Hi!

I'm using your Initial Request feature to GET some response. But when i'm trying to read the response body, i got _"Body has already been consumed"_ error
![image](https://user-images.githubusercontent.com/19486056/230590756-1dbb3acb-4a4f-43fc-bb67-50fbe07d8797.png)

```
Promise { <state>: "rejected", <reason>: TypeError }
​
<state>: "rejected"
​
<reason>: TypeError: Response.text: Body has already been consumed.
​
<prototype>: Promise.prototype { … }
7601.064cc75d586bff6ad076.js line 2 > eval line 2 > Function:6:9
```

On the Update Request feature, the code works just fine (I can read the response body)

Is this a bug? Or do I use it wrong?

PS: really great plugin btw! i'm using it now to build my side project, really appreciate it!

**Comment by mikhail-vl** [comment]
@joshuakosasih, the response from the Initial request is parsed automatically when using `GET`and set as the `initial` parameter available to use in the code: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/

  Let me know if there is anything else.
