### ISSUE TITLE
Is there a way to force the Sections Layout to stack vertically rather than horizontally?

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#154]
I am using the "Section" Layout and I am wondering if there is a way to force a vertical layout for the Sections rather then horizontal.

Thanks,
-Ray

**Comment by mikhail-vl** [comment]
@rantinray I will add the option in the upcoming release.

**Comment by rantinray** [comment]
@mikhail-vl Thank you.  This plugin has been very helpful.  I really appreciate the quick feedback.

-Ray
