### ISSUE TITLE
Bug in Data Manipulation: Type Date and Time from Form Elements

### ISSUE THREAD

**Issue by pksoluciones00** [VolkovLabs/volkovlabs-form-panel#156]
In Data Manipulation Plugin, in Date and Time Form Elements, I can change the dates when I press the Apply Button, but I cannot change the time. The time always keeps the value from the actual value.

![Manipulation Data Bug](https://user-images.githubusercontent.com/116191650/232104912-f87fe431-e2a3-41eb-bdbd-4b3a8ca9f337.png)

I hope you can fix this because it seems to be such a great in grafana.

Regards.

**Comment by mikhail-vl** [comment]
@pksoluciones00 Thank you for reporting the issue. I will take a look.

**Comment by mikhail-vl** [comment]
Seems to be fixed in Grafana 9.5.0:

```
### Plugin development fixes & changes

 - **DateTimePicker:** Can now select time correctly. [#65428](https://github.com/grafana/grafana/pull/65428), [@eledobleefe](https://github.com/eledobleefe)
```

**Comment by mikhail-vl** [comment]
@pksoluciones00 We updated Data Manipulation panel to the Grafana 9.5.1 libraries, which have this issue fixed.

  Could you please verify and let me know if it works for you. You can find the latest build artifact in the CI workflow: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/4847924407

**Comment by mikhail-vl** [comment]
@dsocias-tpz Please open new issue what you see in G12, because the original issue was fixed.
