### ISSUE TITLE
error Update An error occurred updating values

### ISSUE THREAD

**Issue by heidymunevar1** [VolkovLabs/volkovlabs-form-panel#157]
I have a problem making the connection between the table to which I want to send the data and the table make a recalculation and show me the new data already calculated with the value that I'm sending every time I try to do this I get the following error Update An error occurred updating values. one thing to note from the table to which I want to connect from the plugin data manipulation this table is fed by an external database from the cloud. how could I fix this error? or that another way to do this process? I hope you can help me with this. Thanks 
<img width="907" alt="Error Grafana" src="https://user-images.githubusercontent.com/128732926/232805270-db30af0c-bc1c-4c4f-9f6b-03920bae28b5.png">

**Comment by mikhail-vl** [comment]
@heidymunevar1 Do you see any issues with the Initial request in the Browser Console or Network tab?

  The panel can't reach or understand the Initial Response and fails.
  Let me know if it helps.

**Comment by heidymunevar1** [comment]
Yes in this part I am not 100% sure because my local host is different but I tried putting the two options the local host you see now in the image and also the one in the direct URL of our Grafana page in both cases I got the same error.
<img width="957" alt="Error Grafana 2" src="https://user-images.githubusercontent.com/128732926/232835881-aa461c9d-7e9e-4572-97a3-35eb6bade162.PNG">

**Comment by mikhail-vl** [comment]
@heidymunevar1 Data Manipulation expects to have an API Server. Where is your API server running? Does it use port 3000, or it's a Grafana port?

  Have you seen the YouTube tutorial on how the panel works? We also have documentation with examples https://volkovlabs.io/plugins/volkovlabs-form-panel/

**Comment by mikhail-vl** [comment]
I hope it works for you.

**Comment by heidymunevar1** [comment]
Hi mikhail thanks for your support on this issue, I wanted to tell you that we have a question regarding a step of the connection process of the plugin where it is mentioned that you must change API REST and specify the INSERT statement in the POST section this configuration has not been possible to find it in Grafana would like to know in which section I can view and change this exactly because the video does not show how to enter or access this function of grafana. If you could help us with this it would be very useful for the issue we currently have. 
<img width="960" alt="GRAFANA" src="https://user-images.githubusercontent.com/128732926/233478746-4875c2a7-3196-44f9-846d-48fbe29456ad.png">

**Comment by mikhail-vl** [comment]
@heidymunevar1 Data Manipulation was designed to work with API Server. We have examples for PostgreSQL, MySQL, InfluxDB and others in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/#api-servers

  There is a way to work directly with data sources, and we are working on adding it to the documentation.

**Comment by mikhail-vl** [comment]
@heidymunevar1 I hope Spanish auto-translated subtitles in YouTube tutorials help to find answers to your questions.

**Comment by heidymunevar1** [comment]
Hi Mikhail yes we are working on the API in PostgreSQL but my question is that part of the pluglin I can modify this code I cant find this option anywhere in Grafana and my second question is regarding the Update Request because I need to define a variable which I want to make a POST as would be done in postman or python I cant find the option where you must define that variable of the function that we are modifying. 

<img width="535" alt="UPDATE REQUEST" src="https://user-images.githubusercontent.com/128732926/234109542-7b74f405-7b23-4941-8f92-cc825b91a5aa.PNG">
<img width="763" alt="POSTGRESQL" src="https://user-images.githubusercontent.com/128732926/234110085-160e09c1-dd76-4825-af84-aeb6f466b54a.PNG">

**Comment by mikhail-vl** [comment]
Data Sources were added for the Initial and Update requests in v3.1.0.
