### ISSUE TITLE
Special characters (from variables) in URL's aren't being encoded

### ISSUE THREAD

**Issue by apellew** [VolkovLabs/volkovlabs-form-panel#160]
I have created a dashboard variable called "varTest" of type text box and set it to "`test variable name with spaces and /?& special codes`".

The URL I'm using (update request POST) is;
`http://localhost:8000/call/${varTest}/`

I have created a simple logging service that logs whatever is passed in.

When I look at the output I get;

`2023/04/20 14:48:36 [::1]:50718 POST /call/test%20variable%20name%20with%20spaces%20and%20/?&%20special%20codes/`

This shows that the spaces are being correctly encoded - but the special characters are not.

(for reference our API's work by separating the values with "/"'s - `call/{site}/{project}/{user}/{notes}/` - so having a `/` appear unexpectedly in the middle of a value means the call fails)

See https://www.w3schools.com/tags/ref_urlencode.ASP for expected encoding details.

If you'e thinking we could use variables instead (i.e. `call?note={notes}`) but then we just change the `/` problem for an `=` problem.

**Comment by mikhail-vl** [comment]
@apellew Thank you for reporting this. We need to add encoding the URL with variables.

  It should be easy to implement. I will plan for the upcoming release.
