### ISSUE TITLE
date element bug or question

### ISSUE THREAD

**Issue by farmboy-dev** [VolkovLabs/volkovlabs-form-panel#161]
Hi
Thank you for the great plugin.
Finally, I can insert user input data into my db, but when I added date element, I got a KeyError in Flask (KeyError: 'created_At') and "An error occured updating values"
I'm using SQLite and Python Flask.  I tested two data type (TEXT, BLOB)
![image](https://user-images.githubusercontent.com/70833564/233499112-ae391730-0ce7-4553-893c-9003e430827a.png)

**Comment by farmboy-dev** [comment]
Thank you so much.
I'm not sure, but it might be sqlite problem related to data type.
Anyway, I decided to save date on the server side. 
Thank you for the help and wonderful plugin!

**Comment by mikhail-vl** [comment]
@farmboy-dev Do you mind sharing your Flask + SqlLite code to add to the documentation?
