### ISSUE TITLE
How do I use this plug in to refresh a grafana table based on a user generated search request?

### ISSUE THREAD

**Issue by tmuhamma** [VolkovLabs/volkovlabs-form-panel#162]
I would like to submit a REST API request via the plug in, then show the results from the request in a grafana table. How can I do this? Mostly confused on the refreshing+showing data in a Grafana table part.

**Comment by mikhail-vl** [comment]
@tmuhamma We explained it in the YouTube Tutorials and documentation with examples: https://www.youtube.com/watch?v=DXALVG8GijM

  You can execute any custom code after the request to reload the dashboard and display the results: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#refresh-dashboard-after-update-request-or-show-error

  Let me know if it helps.

**Comment by mikhail-vl** [comment]
Let us know if there is anything else.

**Comment by tmuhamma** [comment]
Hi Mikhail, I wasn't able to get this working with the documentation provided. I am trying to do something pretty basic. I load up https://dummyjson.com/products in a Table (using Infinity Table datasource), and want to use the Data Manipulation plugin to pass in a user inputted "search" variable to the Table, so I can refresh the dashboard and load up 

https://dummyjson.com/products/search?q=VARIABLE 

instead of https://dummyjson.com/products.

Is this possible?

**Comment by tmuhamma** [comment]
Any examples would be appreciated!

**Comment by mikhail-vl** [comment]
@tmuhamma To update the variable for the search, I would not recommend using the Data Manipulation panel.

  It's possible with a custom code to update the dashboard variable on an update request similar to: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-variable-after-update-request-to-interact-with-other-panels

  I would suggest to look at the variable panel instead. It allows you to enter a custom value for the dashboard variable, which you can use in the request to the Infinity Data Source: https://volkovlabs.io/blog/variable-panel-1.6.0-20230726/#input-text-box.
