### ISSUE TITLE
select with custom option is not working 

### ISSUE THREAD

**Issue by farmboy-dev** [VolkovLabs/volkovlabs-form-panel#164]
Hi 
I can't select another option. 
This is my setting.
![image](https://user-images.githubusercontent.com/70833564/233688157-4c581112-97cb-406b-b369-c4e2a5b48fb2.png)

**Comment by mikhail-vl** [comment]
@farmboy-dev I need more information.
 1) What is the error you see in the upper-left corner?
 2) How did you define the `test` element?

**Comment by farmboy-dev** [comment]
Thank you for quick reply.
that is my fault, I didn't add value to each label.
