### ISSUE TITLE
Host problems

### ISSUE THREAD

**Issue by Cito-98** [VolkovLabs/volkovlabs-form-panel#167]
Hi, I've have an issue about the url you use for the update requests. I tried using localhost the way you explained in your videos, but it doesn't seem to work in other machines. Also when I tried setting up the api server in another machine it worked on postman but it didn't on grafana.

**Comment by mikhail-vl** [comment]
@Cito-98 `localhost` is applicable only if you develop locally. To connect from other hosts, you should use the proper DNS name.

  Grafana may be unable to reach the API server, or it has issues connecting like CORS, which we explained in videos and documentation (https://volkovlabs.io/plugins/volkovlabs-form-panel/). You can troubleshoot the network issues using Browser Console -> Network tab.
  Let me know if it helps.
