### ISSUE TITLE
How to update Text Area from GET request?

### ISSUE THREAD

**Issue by mikequentel** [VolkovLabs/volkovlabs-form-panel#169]
Not sure if this is possible with *Data Manipulation Plugin*, but would like to update a **Text Area** based on information from GET requests to the REST API of an Artifactory server. Not clear how I am supposed to use custom code to modify the behaviour. How does one do this? Can it be done through the user interface of the panel, or does one use this plugin as a framework where changes are made to the plugin code? Maybe this plugin is meant to be used in conjunction with another plugin that would act as the read-only view (eg: Table Panel with a JSON data source)?

Upon initial request, I can see the `console.log` successfully showing response from the **URL** input.

When I attempt to change **Custom Code** in the **Initial Request** section, it always reverts to `console.log(data, response, initial, elements)`

Screenshot of the form; would like "properties" to get updated with data from a GET request.

![form_with_textarea](https://user-images.githubusercontent.com/5436386/234756756-44b91b17-43df-402c-8eac-51b94369e5a8.png)

Related details:
* Artifactory and Caddy (reverse proxy to enable TLS for Artifactory) run as Docker containers.
* CORS being handled by Caddy.

Many thanks!

**Comment by mikequentel** [comment]
@mikhail-vl many thanks. The PR looks like a good idea, especially as I prefer to read documentation, than watch a video, to find this information; I can more easily search a document than a video.

**Comment by mikhail-vl** [comment]
@mikequentel I hope it's clear now and you can move forward.

  Appreciate the feedback. Everybody learns differently, and we do our best to keep videos and documentation updated to answer as many questions as possible.
