### ISSUE TITLE
Is there a way to use the time picker with "custom formats" like: "MM/yyyy"?

### ISSUE THREAD

**Issue by fercasjr** [VolkovLabs/volkovlabs-form-panel#173]
Not a big problem, I could do some code to get only the month of any given selection or use a drop-down menu for Month and Year too, but it would be more aesthetic and user-friendly to have that option, also maximum and minimum dates would be nice to have.
In my use case, I require a form to input monthly "target" values that will be utilized in various dashboards..

**Comment by mikhail-vl** [comment]
@fercasjr `DateTimePicker` from Grafana-ui component supports Min and Max dates. Will be easy to add. in the panel options.

  There is a DatePicker (https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-datepickerwithinput--basic), which can be used, but I don't see custom formats supported. You still have to pick a day.
