### ISSUE TITLE
Consider adding additional Set/Clear buttons

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#174]
Consider adding additional [optional] buttons like the "Reset" button. These buttons "Set" and "Clear" could be enabled/disabled like the "Reset" button, but have a code panel linked to them so the user could explicitly set/clear all values in the panel.  Maybe just 2 additional buttons linked to a code panel that the user could title whatever they liked.

Thanks,
-Ray

**Comment by mikhail-vl** [comment]
@rantinray Thank you for the request. We added a custom code for the Reset button to Set, Clear form elements.

  It's available in the upcoming release 3.1.0.
