### ISSUE TITLE
Multiple lines in read-only or read-only in text area

### ISSUE THREAD

**Issue by sergeydmit** [VolkovLabs/volkovlabs-form-panel#176]
My REST API server returns multiple lines text that should be shown but not edited by user.
Current implementation of Read-only element ignores/removes "\n" making returned results almost unreadable (200+ characters as one line). Text Area element shows these results without issue, but allows editing.

So, what makes more sense in subj.?

Sergey

**Comment by sergeydmit** [comment]
It would be great if "monospaced" font could be an option for this to display "tabulated" output.

**Comment by mikhail-vl** [comment]
@sergeydmit I think read-only text area makes more sense.

  I will look into font as well.
