### ISSUE TITLE
How do I extract return value after doing POST?

### ISSUE THREAD

**Issue by akshay996** [VolkovLabs/volkovlabs-form-panel#177]
I am currently doing a POST response by inputting values from Data Manipulation form panel and through my backend script, I am returning "response message" as a return value for it to be shown on Grafana Dashboard as a success message via "notifySuccess" function. I can see through my browser Developer Tools (in the Network Tab) that I am getting a response back (screenshot below) but I am not able to figure out how to assign that message to Data Manipulation plugin variable so that it can be used to generate notifySuccess message?

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/59548002/785c907c-eb99-46c8-a408-98dd5dbcb19a)

Any help would be appreciated!

**Comment by akshay996** [comment]
Got the answer from another GitHub issue -> https://github.com/VolkovLabs/volkovlabs-form-panel/issues/93

You can wrap the return value in a json and extract it in the front-end

**Comment by mikhail-vl** [comment]
@akshay996 Glad you resolved it yourself. I have to check if we mention it in the documentation. If not, I will add it.

  Let us know if there is anything else.

**Comment by vanimesh** [comment]
@akshay996 , how were you able to  pull the response from the post response ? I am trying to do it but i always get as {}. But in postman i get the proper response.

Any help from @mikhail-vl is really appriciated.

**Comment by mikhail-vl** [comment]
@vanimesh Do you see response's data in the Browser's network? If you don't see it then your endpoint does not return the correct data.
