### ISSUE TITLE
Having trouble to make PUT REST call work in Data manipulation Panel 

### ISSUE THREAD

**Issue by ManiAm** [VolkovLabs/volkovlabs-form-panel#178]
I am running a flask-based REST server on my local machine.

I do not get any response when using the "Data manipulation" plugin.
Grafana is installed on the same machine.

Here is plugin config:

![2023-05-17_19-10-34](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/5473998/0bba8058-e384-4b17-b46e-416e88ec7f37)

and chrome dev view:

![2023-05-17_19-10-48](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/5473998/0b9f38e3-7847-4f17-90c1-5a59ef5ecf9e)

when I click on submit, it just get stuck and eventually shows:

`error getting data frame. error getting response from url http://localhost:5000/telemetry/api/v1.0/test. no response received. Error: Get "http://localhost:5000/telemetry/api/v1.0/test": dial tcp [::1]:5000: connect: connection refused`

I can perform GET and PUT requests using `curl` on the same machine.

    curl -i -X GET http://localhost:5000/telemetry/api/v1.0/test

    curl -i -X PUT -H 'Content-Type: application/json' -d '{"name":"william", "age":54}' http://localhost:5000/telemetry/api/v1.0/test

what am I missing here?

**Comment by mikhail-vl** [comment]
@ManiAm I hope you resolved your issue. `localhost` for you differs from the server you are working on.

  Data Manipulation is connecting to the API endpoint from the browser. So it should be an IP address or the domain name.
