### ISSUE TITLE
Storing secrets for API authentication

### ISSUE THREAD

**Issue by vdwpsmt** [VolkovLabs/volkovlabs-form-panel#182]
Hi, 

In the custom request example you use a variable $token.  I suppose this is a dashboard variable?  If so, how do I store this in a safe way?

[custom requests](https://volkovlabs.io/plugins/volkovlabs-form-panel/request/)
```
const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "PRIVATE-TOKEN": "$token",
  },
```

**Comment by mikhail-vl** [comment]
@vdwpsmt You can retrieve it from the data source or dashboard variable using the data source.

  The most secure way is to use the custom data source in a proxy mode, as we described in blog post https://volkovlabs.io/blog/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904/

**Comment by mikhail-vl** [comment]
Using Data Sources for Initial and Update requests introduced in v3.1.0.
