### ISSUE TITLE
Data manipulation connection with influxdb

### ISSUE THREAD

**Issue by di7wal** [VolkovLabs/volkovlabs-form-panel#189]
Hello dears,
I introduce myself, I am Darwin and I am not a programmer. But so far I have been able to launch influxdb with grafana and installed Data manipulation. But I need help that's why I contact you. I need an example of how to send a number input to influxdb. If you can share an example it would help me a lot. From already thank you very much.

**Comment by mikhail-vl** [comment]
@di7wal, We have an example with InfluxDB API in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/servers/influx/

  We plan to add a connection to the data source in the upcoming release, which can be another option for InfluxDB.

**Comment by di7wal** [comment]
Okay. Thank you very much for your prompt response. I was already looking at that available information. But I thought there could be something simpler for this connection. Thank you very much again.

**Comment by mikhail-vl** [comment]
@di7wal Direct connection to the data source should be more accessible. I hope to finish it this week in v3.

**Comment by mikhail-vl** [comment]
Resolved in https://github.com/VolkovLabs/volkovlabs-form-panel/pull/222
