### ISSUE TITLE
Add multi select dropdown

### ISSUE THREAD

**Issue by ashleymcdonald** [VolkovLabs/volkovlabs-form-panel#194]
We often need the ability to select multiple options from a list.

Our current solution is to use Grafana variables at the top of the page and add them to the request, but this is not the best workflow, as changes will affect the dashboard before the request is sent.

Would it be possible to add the multi-select from @grafana/ui to the available options; it could work the same as the current select as for configuration and submit an array of the variable name.

Docs for reference: 
https://developers.grafana.com/ui/canary/index.html?path=/docs/forms-select--docs#multiselect

**Comment by greasyfamilyzhi** [comment]
Agree!

**Comment by mikhail-vl** [comment]
@ashleymcdonald @greasyfamilyzhi Thank you for opening the feature request.

  I will plan to add it in the upcoming version.
