### ISSUE TITLE
Fetch from Grafana and not from browser

### ISSUE THREAD

**Issue by ctison** [VolkovLabs/volkovlabs-form-panel#195]
Hello,

Grafana is running inside a VPC and I would like to interact with an API only available inside the VPC, would it be possible to implement (or is it already)?

### Examples
- https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/
This plugin allows to make the query through the backend.
- https://grafana.com/grafana/plugins/speakyourcode-button-panel/
This plugin allows to trigger a datasource.

Great software, it makes grafana more like a retool ;)
Thank you

**Comment by mikhail-vl** [comment]
@ctison It's a great question, and it was requested multiple times.

  I like how the button panel used the data source and we will do the same.

**Comment by mikhail-vl** [comment]
We implemented various JavaScript hooks and refactored element states in v3.
Using Data Sources for Initial and Update requests introduced in v3.1.0.
