### ISSUE TITLE
Authentication to Get/Post Request

### ISSUE THREAD

**Issue by dipeshtripathi** [VolkovLabs/volkovlabs-form-panel#199]
Hi, 

How can we add authentication to the Get/Post request? We dont want to store credentials on the client because thats a security risk.

Is there any datasource way of storing these credentials? Something similar to infinity ds plugin?

**Comment by mikhail-vl** [comment]
Data Sources of the Initial and Update requests implemented in v3.1.0.

**Comment by diptripa** [comment]
Hi @mikhail-vl , Can you help me by pointing to any documentation on how we can do this? I tried installing the latest plugin, but doesnt seem to be working right now. i.e., no option to add data source for auth.
