### ISSUE TITLE
Problems trying to update the panel

### ISSUE THREAD

**Issue by nicomar2000** [VolkovLabs/volkovlabs-form-panel#211]
Can not update elements on Initial Request after release 3.0.0.
This is my script in the initial request:
```
 options.elements.forEach((element) => {
    if (element.id == "question") {
      element.value = 'test'
    }
  });
  onOptionsChange(options);
```

If I try editing the visualization, in the edit section, I can see the elements updating, but it doesn't work when I change I variable or load the dashboard.

**Comment by mikhail-vl** [comment]
@nicomar2000 We updated Data Manipulation to use local states instead of directly updating dashboard options in the dashboard.

  Probably, updating options directly does not re-render the panel and you don't see.
  @asimonok Please check.

**Comment by mikhail-vl** [comment]
@nicomar2000 The problem is a mutation, which we eliminated in v3.. Using immutable updates fixes the issue.

```
onOptionsChange({
  ...options,
  elements: options.elements.map((element) => {
    return element.id === 'name' ? { ...element, value: 'test' } : element
    })
});
```

I will update the documentation that options should be updated without mutations.
Let me know if it works for you.

**Comment by nicomar2000** [comment]
@mikhail-vl thank you, that fix my problem with the new version of this plugin.

**Comment by nicomar2000** [comment]
@mikhail-vl this is probably a very noob question but how can I edit multiple element? in that example we can edit an element with specific ID, how could I edit multiple ID in the same loop?

**Comment by mikhail-vl** [comment]
@nicomar2000 This should work:

```
onOptionsChange({
  ...options,
  elements: options.elements.map((element) => {
      if (element.id === 'name') {
         return { ...element, value: 'test' };
      } else if (element.id === 'name2') {
         return { ...element, value: 'test2' };
      }
      
      return element;
    })
});
```

  Let us know if there is anything else.
