### ISSUE TITLE
Retrieve data from elements

### ISSUE THREAD

**Issue by nicomar2000** [VolkovLabs/volkovlabs-form-panel#212]
I was able to get the elements value with the following snip before version 3.0.0
```
options.elements.forEach((element) => {
  console.log( element.id + '= ' + element.value );
})
```
This is no longer working for elements values that where populated manually and then submitted, but it work for values that where populated with the initial request script.

**Comment by nicomar2000** [comment]
NVM, this worked for me:

```
elements.forEach((element) => {
  console.log( element.id + '= ' + element.value );
})
```

**Comment by mikhail-vl** [comment]
@nicomar2000 That's the correct approach for v3 to use elements in the local state instead of options.

  Let us know if there is anything else.
