### ISSUE TITLE
How to process the response in json in java script

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/volkovlabs-form-panel#213]
How to process the response in json in java script? When i test the url using postman i get the respose(when not 200) in form of json. Is there any way to get the data and show it ? something like this ?

if (response && response.ok) {
  notifySuccess(['Update', 'Requested accepted successfully.']);

} else {
  notifyError(['Update', response.json()]);
}

**Comment by mikhail-vl** [comment]
@vanimesh Data Manipulation panel does not parse the json content of the response. You should parse it yourself like:

```
if (response && response.ok) {
  response.json().then(resp => {
    console.log(resp);
    locationService.partial({ 'var-vartest': resp['name'] }, true);
  });
}
```

  It's a part of the documentation, but it does not provide details: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-variable-after-update-request-to-interact-with-other-panels. I will fix it.
