### ISSUE TITLE
Data_Manipulation Plugin_Reset Option_not able to set

### ISSUE THREAD

**Issue by tamilmozhiiplon** [VolkovLabs/volkovlabs-form-panel#218]
Hi, 
Using Data manipulation plugin, I have created form element using " **SELECT WITH CUSTOM OPTION**" with \
type =number, when I Click on the Update button, the selected value will be writing into the API for the Specified id,
 
 My requirement is, when I have click in the **RESET** Button, the first configured OPTION should be selected and automatically write in the given URL.
 
 My update Request Function seems:

**const body = {};

options.elements.forEach((element) => {
  if (!options.update.updatedOnly) {
    body[element.id] = element.value;
    return;
  }

  // Skip not updated elements
  if (element.value === initial[element.id]) {
    return;
  }

  body[element.id] = element.value;
  console.log('element', element);

});

// Check if the reset option is selected

// Set URL
const url = `http://localhost:111/data/setting?id="xx"&element.id=${body["val"]}`;
console.log("Updated URL:", url);

// Fetch
fetch(url, {
  method: "POST",

})
  .then((response) => {
    if (response && response.ok) {
      notifySuccess(["Update", "Values updated successfully."]);
      initialRequest();
    } else {
      notifyError([
        "Error",
        `An error occurred updating values: ${response ? response.status : "Unknown"
        }`,
      ]);
    }
  })
  .catch((error) => {
    console.error(error);
    notifyError(["Error", "An error occurred during the request."]);
  });**

**Comment by mikhail-vl** [comment]
@tamilmozhiiplon I was planning to add a custom code for the reset button. Will it work for your use case?
