### ISSUE TITLE
Ability to add image as forum Label

### ISSUE THREAD

**Issue by ashish-y** [VolkovLabs/volkovlabs-form-panel#223]
Feature Request:
Ability to add image as forum Labels

I would like to propose an enhancement that enables the ability to add images as form element label.
For instance, on custom radio button element, the user has an option to use an image as a label instead of text.

**Comment by mikhail-vl** [comment]
@ashish-y Thank you for submitting feature request.

  We will look into adding an option to use available Grafana icons for labels.
