### ISSUE TITLE
Initial Request does not load automatically unless Reset button is pressed in v3.1

### ISSUE THREAD

**Issue by akshay996** [VolkovLabs/volkovlabs-form-panel#226]
I have a working Data Manipulation Plugin (DMP) panel at another plant which is running on v2.8 and is working great. But when I am trying to replicate that panel into a new plant site where I recently downloaded v3.1 DMP, Initial Request code does not run unless I explicitly call "Initial Request" by pressing Reset Button.

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/59548002/b220bd31-d455-45be-94f8-f50f6564ea6d)
Fields "Asset" ,"Date" and "Shift" are Read-only form elements and their values are dynamic based on dashboard variables and current date. 

Currently, upon dashboard load, all these elements are blank unless I press Reset Button, upon which the initial request code works. I know that some new changes have been implemented in v3.0+ regarding values in local state but I didn't understand it fully, so can anyone please explain what changes I should make in my code? Also using "Save Default" button won't work for my case as I want Shift and Date fields to show today's date as per the script I have written in "Initial Request" section. 

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/59548002/5b9f0659-15e5-4a03-ad73-bd5b3323fd84)
This was how I was initializing form elements value in v2.8

**Comment by mikhail-vl** [comment]
@akshay996 We introduced the local state in v3.1.0 instead of using panel options.

  Use 'onChange' to update values as described in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-local-state-in-v310
