### ISSUE TITLE
Assign initial request value to form element

### ISSUE THREAD

**Issue by RyIot3329** [VolkovLabs/volkovlabs-form-panel#235]
How to go about assigning the value received from the initial response to one of the form elements?

**Comment by mikhail-vl** [comment]
@RyIot3329 We updated the Data Manipulation to use local state instead of panel options.

  Use 'onChange' as described in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-local-state-in-v310
