### ISSUE TITLE
Fill element value with dashboard variable

### ISSUE THREAD

**Issue by Radrik5** [VolkovLabs/volkovlabs-form-panel#239]
I would like to copy value from dashboard variable. I added single String Input element and this code to Initial Request:
```
setInitial({ active: "${host}" });
elements[0]["value"] = "${host}";
```
It even seems to work in the panel edit mode (when I change variable, the value changes).

But when I close the edit mode, it does not work in the dashboard: the input stays empty. I tried adding the same code to the reset button and it works better (it does change the input value).

### Why did I need dashboard variable in the first place?

I need a drop down list filled with elements from query response. The user selects one of them and presses the button. Ideally, the list should be editable to allow custom values.

"Select with Custom options" has static list of options, so I though I could use dashboard variable (possible with the Variable plugin) and pass its value to the Data Manipulation plugin.

**Comment by mikhail-vl** [comment]
@Radrik5 To set element values in Data Manipulation v3 use, which will update the local state for the elements. Updating elements directly mutates them and does not persist.

```
onChange(elements.map((element) => {
  return element.id === 'name' ? { ...element, value: 'test' } : element
});
```

  Select and Multi-select elements from query response will be implemented in the upcoming version: https://github.com/VolkovLabs/volkovlabs-form-panel/issues/240

**Comment by Radrik5** [comment]
@mikhail-vl thanks a lot! The code works and after reading #240 I managed to get what I initially wanted.

**Comment by mikhail-vl** [comment]
@Radrik5 Thank you for confirming. Glad it worked for you.
