### ISSUE TITLE
Multiselect - add query from datasource option

### ISSUE THREAD

**Issue by henjoe** [VolkovLabs/volkovlabs-form-panel#240]
Other than adding value selections manually, add options to get the list from a query.
For example:

"SELECT city FROM Country" 

and will return list of city as the selections in thr multi-select.

**Comment by jacksongoode** [comment]
We've also looked at this. One way to do this is to reference a dashboard variable (like `$dash_var`) that does this query, assign it to a JS object, and then append it to the form elements (`elements` in JS) of the dropdown like https://volkovlabs.io/plugins/volkovlabs-form-panel/dynamic/.

The issue only issue I have with this is that is that you can only feed in dashboard variables after the first initial request. It would be nice if this could happen on dashboard load.

**Comment by jacksongoode** [comment]
Update: You can use `onChange(elements)` where you've modified you elements to map to the Grafana dashboard vars and they will appear initially.

**Comment by mikhail-vl** [comment]
@henjoe @jacksongoode Thank you for the feature request. It's possible to do it with custom code as described in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/dynamic/ 

  We plan to implement the UI options in the upcoming release, similar to the Initial Request using Query.

**Comment by Radrik5** [comment]
For those who needs more examples (like me), this code loads list of options from a data source:

```
const hosts_ds = data.series.find((serie) => serie.refId === "A");
if (hosts_ds?.fields.length) {
  const hosts =
    hosts_ds.fields.find((f) => f.name === "hosts").values.buffer ||
    hosts_ds.fields.find((f) => f.name === "hosts").values;

  elements = [{
    id: 'active', title: 'Host', type: 'select',
    options: hosts.map((host) => {
      return { id: '', value: host, label: host, type: 'string' }
    })
  }];

  onOptionsChange({ ...options, elements });
}
```

How the code is connected to the data source: https://youtu.be/RSVH1bSBNl8?t=53

**Comment by mikhail-vl** [comment]
@Radrik5 Thank you for sharing the example until we implement this feature.
