### ISSUE TITLE
Soft refresh trigger

### ISSUE THREAD

**Issue by jacksongoode** [VolkovLabs/volkovlabs-form-panel#241]
Currently we are using `locationService.reload()` to load a panel after data has been inserted into it. However, this causes the entire dashboard to reload all panels rather than just refresh the queries made from each panel. It would be nice to perform this soft reload like when you click on the spinning arrows with tooltip "Refresh dashboard". I'm not sure if this function is exposed to plugins but I imagine it might be.

**Comment by asimonok** [comment]
@jacksongoode thank you for the request.
Grafana doesn't allow to make "soft" dashboard refresh from the panel's code. So probably using `locationService.reload()` is the best option here.

**Comment by mikhail-vl** [comment]
@jacksongoode As @asimonok there is no "soft" refresh.

  You may try to update dashboard variable using `locationService` which can trigger Data source's query update and re-render panel. If it's what you are looking for.

**Comment by imReker** [comment]
Do you mean:
`$('.refresh-picker button')[0].click()`
?

**Comment by jacksongoode** [comment]
Yeah that might be it!
