### ISSUE TITLE
Can't link PSQL query to inital request 

### ISSUE THREAD

**Issue by gerrygralton** [VolkovLabs/volkovlabs-form-panel#245]
Hi,
I'm almost certainly doing something incorrectly but I have a PostgreSQL database set up on a remote server which can be queried by grafana. When I try to integrate these queries into a data manipulation dashboard, I was expecting to see a Query option under initial request but it is not there. This is how it is done in your explainer video. What am I doing incorrectly?

The only options I see under initial request are `-`, `Data Source` and `GET`.

**Comment by mikhail-vl** [comment]
@gerrygralton Plugin is still under Grafana review to update in the Grafana Catalog.

  Meanwhile, you can download and install directly from GitHub.
