### ISSUE TITLE
Data Manipulation Plugin Not Displaying Leading Zeroes for Float Values while input 

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#247]
Hello Volkalabs Community,

I’m currently using Grafana with the Data Manipulation plugin (version 3.1.0), and I’ve come across an issue that I’d like to discuss with you. When I choose the “number” format to display float values, the plugin is not showing leading zeroes for values less than 1. For instance, 0.5 is displayed as “.5,” and I would like it to show as “0.5.”

I kindly request your assistance and insights. If you’ve encountered a similar problem or have suggestions for a resolution or workaround, please share your knowledge.

Best regards,
Utkarah

#volkalab #data_manipulation

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe Thank you for opening the issue. We will check and get back to you.

**Comment by utkarshsalunkhe** [comment]
@mikhail-vl  is any update about this issue ?

**Comment by asimonok** [comment]
@utkarshsalunkhe we will add the new number field control in the upcoming release. It will solve the issue

**Comment by mikhail-vl** [comment]
Resolved in #291
