### ISSUE TITLE
Create and Delete request compatibility

### ISSUE THREAD

**Issue by jacksongoode** [VolkovLabs/volkovlabs-form-panel#248]
We are trying to have one panel allow a submit and delete. However the delete button doesn't appear to function properly.

```js
// Custom Code
const id = "$note_id";

try {
  return {
    rawSql: `delete from field_notes where id = ${id}`,
    format: 'table',
  };
} catch {
  console.log(e)
  notifyError(['Failed', 'An error occurred deleting values.']);
}
```

I'm not sure if there needs to be an option for a `Data Source` request type for the alternative buttons? Or if you would recommend using a separate panel for this.

**Comment by mikhail-vl** [comment]
@jacksongoode Did you call reset a `delete` button, or how did you implement it?

  Could you please explain your use case? I was thinking about adding an additional button like submit with custom payload, and data source to support additional requests. Will it work for you?

**Comment by jacksongoode** [comment]
Yes, exactly I had repurposed the reset button to serve as a delete. I think what you imagine would satisfy my use case.
