### ISSUE TITLE
Issue while uploading the file

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/volkovlabs-form-panel#249]
Hi Team,

I always get the message "Upload failed File type must be application/octet-stream". When i try to upload the files. Can i have the detailed steps to use this?

**Comment by mikhail-vl** [comment]
@vanimesh We are working on updating documentation for the latest release. Are you using REST API or Data Source requests? Where do you see this error?

  For REST API, you can choose Content-Type `application/json` to send the file as Base64 encoded.
  If you choose `multipart`, it's sent as a binary file. Seems to be your case.

**Comment by vanimesh** [comment]
Hi @mikhail-vl , the message pops up right after I upload the file

**Comment by mikhail-vl** [comment]
@vanimesh Please answer all questions.

**Comment by vanimesh** [comment]
We are using API. I am sorry i am beginner on this things. My goal is to upload the csv file and when clicked it has to call a restAPI which inturn calls the python script.

**Comment by asimonok** [comment]
@vanimesh seems to be the API to where you try to send the csv file doesn't accept the real MIME Type of file (`text/csv`). Please adjust your API to accept `text/csv` or if you use any existing API/service please let us know and we will consider to add supporting it

**Comment by vanimesh** [comment]
Hi @asimonok , i tried to check and script seems to be fine. But seems like the plugin itself is not sending any data . Its just calling the api. When i tried to print the post data from the script its empty everytime.
