### ISSUE TITLE
Resolve Localhost in REST API

### ISSUE THREAD

**Issue by daguirrem** [VolkovLabs/volkovlabs-form-panel#250]
Hello

I had a problem with the real locahost resolve.

Context:
I use the plugin to write some information from user to influxDB data base throught custom code post request. the POST request point to https://localhost:8086/api/v2/write?org=my-org&bucket=example-bucket (for example) URL. Grafana and influxDB are on same instance, the problem is localhost is resolving to my real local computer (where i am accessing to grafana) and not to the instance where influxdb and grafana are installed. How i can to tell to custom code that resolve to instance localhost?

The workarround:
For now i point the POST request to a public influxdb instance url, but for deploy i need the url point to localhost.

thanks you in advance.

**Comment by mikhail-vl** [comment]
@daguirrem If you use REST API, your web browser (frontend) performs the request. You can't use `localhost` in this case. The only solution is to use an external DNS/IP address.

  The latest version 3.2.1 introduced Data source support, which is executed on the backend, and you should consider using it for your use case.
   YouTube tutorial to get started: https://www.youtube.com/watch?v=hVy9NfFiI5U
