### ISSUE TITLE
 Dashboard Refresh Issue: How to Make Data Manipulation Panels Independent of Dashboard refresh?

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#251]
In the latest plugin update, I  noticed that their data manipulation panels, particularly form panels, are being updated automatically when the dashboard is refreshed . This unexpected behavior has caused inconvenience to fill form in panel . form erase everything filled .

**Comment by utkarshsalunkhe** [comment]
Refresh is not freeze while value inputting, value get erase when auto
refresh.

**Comment by wyl1232792** [comment]
Got same problem. Element values are cleaned when grafana refresh triggers.
Is there any elegant solution to avoid this?

I only update "options" in "initial request" logic.

**Comment by utkarshsalunkhe** [comment]
@wyl1232792  i didn't get solution for it , @mikhail-vl please solve this issue.

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe I will look into it.

**Comment by utkarshsalunkhe** [comment]
@mikhail-vl  any update on this issue?

**Comment by asimonok** [comment]
Added a sync option which allows to disable panel updates. It should solve the issue but it also disables following on variable updates.

**Comment by mikhail-vl** [comment]
@Wakaij1n @utkarshsalunkhe Implemented in the upcoming release.

  Meanwhile, you are welcome to test and use for self-hosted Grafana from CI artifact.
