### ISSUE TITLE
File upload issue with Grafana data manipulation plugin

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#252]
I am having an issue uploading files using the Grafana data manipulation plugin. The plugin is uploading the files in a base64 encoded format, but I am having trouble decoding the base64 in my backend.

I have tried decoding the base64 string using different libraries, but I am getting the same error.

I am also wondering how I can get the path of the uploaded file in my backend. I need the path of the file in order to save it to my database.

If anyone has any suggestions on how to fix this issue, please let me know.

**Comment by vanimesh** [comment]
Following as i too have similar requirement.

**Comment by mikhail-vl** [comment]
@asimonok Could you please check.

**Comment by asimonok** [comment]
@utkarshsalunkhe @vanimesh file is sent within array. To get base64 value you have to take `request.file[0] // base64 value`.

**Comment by vanimesh** [comment]
I am using isset($_FILES['fileToUpload']) in my php @asimonok

**Comment by vanimesh** [comment]
and this is how i am testing in postman which works fine
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/49223440/87ddc35b-867c-4835-b4cc-167b3db32f27)

**Comment by asimonok** [comment]
> I am using isset($_FILES['fileToUpload']) in my php @asimonok

Please debug the request payload to see what is the correct field. Please keep it mind that sending files is an array.

In the postman example, it's not array

**Comment by vanimesh** [comment]
> @utkarshsalunkhe @vanimesh file is sent within array. To get base64 value you have to take `body.file[0] // base64 value`.
> 
> In additional, to get file name you should use `Content-type = multipart/form-data` for the updated request

Hi @asimonok , i am using multipart/form-data but it dosent work propely. The files are not getting copied to backend. Is there any example which you tried in your tests ? It would be really helpful for us to learn and replicate. Thank you very much.
