### ISSUE TITLE
Highlight changes does not work with time form

### ISSUE THREAD

**Issue by gerrygralton** [VolkovLabs/volkovlabs-form-panel#256]
When you have a Date and Time form element in a panel, the highlight changes option stops working for all elements in the panel. 

This is using v3.2.1.

**Comment by mikhail-vl** [comment]
@gerrygralton Interesting. Thank you for reporting.

  We will check and get back to you.

**Comment by asimonok** [comment]
@gerrygralton tested on v3.4.0 and it works. Please check on the latest version if the issue exists for you. Probably there are some additional conditions to reproduce the issue. 

<img width="576" alt="Screenshot 2023-12-29 at 10 55 10" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/923e0a93-d3d6-4926-a827-57f4ad251fcf">
