### ISSUE TITLE
is there a way to hide this panel?

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/volkovlabs-form-panel#257]
in some situation, for example, when a read-only reader login, is there any way to hide this panel---- this panel does now show up at all. When an edit/admin user long in, this panel shall show up as normal.
 or a user can decide this panel to show or hide by selecting a dashboard variable(hide/show value)?

**Comment by asimonok** [comment]
@alpglide there is no way to hide the whole panel due to grafana doesn't support that. But you can hide fields if user is not logged in. You have to add the following code in `show if` field for each element

```
return window.grafanaBootData.user.isSignedIn
```

Please let us know if it works for you
