### ISSUE TITLE
Simple arithmetic  operations Supported?

### ISSUE THREAD

**Issue by criticalboot** [VolkovLabs/volkovlabs-form-panel#258]
Can the adjusted KWH value be updated when the adjustment value is changed?

Ref image

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/4224024/a7e86bdd-34c9-4bd0-aa31-62e4bcd1752b)

for example:
If I Enter 10 in the Adjustment value, Expection is to update the adjusted KWH value with 4824
and -10 is the Adjustment value adjusted KWH should be 4804.

**Comment by asimonok** [comment]
It's not supported. It requires field dependencies which is a complex thing and will bring many potential issues

**Comment by mikhail-vl** [comment]
We added On change function, which allows to do it.
