### ISSUE TITLE
Enhancements to  file's upload feature / add Browse file from Local System 

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#259]
Dear Data Manipulation plugin community,

I am writing to suggest some enhancements to the file upload feature. Currently, the plugin only allows users to upload files to Grafana. I would like to propose adding the ability to give the path of the browsed file to the backend. This would be useful for cases where I want to upload a large file from my local system, but I don't want to actually upload the file to Grafana.

For example, I have a large CSV file on my local system that contains data that I want to visualize in Grafana. I would like to be able to browse the file in the Grafana panel and give the path of the file to the backend. The backend could then process the file and generate the visualizations.

**Comment by utkarshsalunkhe** [comment]
Is there any update on this enhancement @mikhail-vl?

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe You can use the Initial Request to display list of files returned from Data Source, Query or REST API and submit it for processing.

  Data Manipulation is a panel which runs in Browser and designed to use REST API or Data Source to interact with backend.

  We may introduce another File Browse panel using WebDAV for processing files on backend, but there is no dates yet.

**Comment by utkarshsalunkhe** [comment]
Hi @mikhail-vl ,

Thank you for the update on the file browse feature. I understand that it's still in the planning stages, but I appreciate you keeping me informed. I would like to reiterate my request for this feature to be implemented as soon as possible. Thank you for your time and consideration.
