### ISSUE TITLE
How to display old values while confirming update change?

### ISSUE THREAD

**Issue by chunyilee71** [VolkovLabs/volkovlabs-form-panel#261]
Sorry, I don't know how to display old values while the confirm update change window pop up.
I would like to query an existing db column value to display as an old value in the confirmation window, but I don't know where I can put my query in order to display it, could anyone help me on this? Thanks a lot!
BTW, I am able to use this panel to update mysql DB column values via a nodejs API server with PATCH and POST APIs.

**Comment by mikhail-vl** [comment]
@chunyilee71 To display old (initial) values, they should be set using `setInitial()` function if you use custom requests: https://volkovlabs.io/plugins/volkovlabs-form-panel/request/#initial-values

  Initial values, should be set automatically when using `GET` REST API or Query requests.
