### ISSUE TITLE
request: global functions available in all instances

### ISSUE THREAD

**Issue by ashleymcdonald** [VolkovLabs/volkovlabs-form-panel#263]
it would be great to define functions available in all instances of the plugin instead of every time in the fields; this makes it hard to maintain as a small change means updating all the places where its used.

ie the following is now in every usage now where we use data source as the initial data.
(assumes the query has the results fields the same as the form.)

```js
function responseAsSomethingUsable(response) {
  const { data, schema: { fields } } = response.data.results.A.frames[0]
  return fields.reduce((agg, { name }, i) => { agg[name] = data.values[0][i]; return agg }, {});
}


function updateElementsFromObject(elements, payload) {
  elements.forEach((element) => {
    if (element.id in payload) element.value = payload[element.id]
  })
}

const payload = responseAsSomethingUsable(response)
updateElementsFromObject(elements, payload)
setInitial(payload)
```

as for these 2 functions potentially you could include helpers for them?

the first (responseAsSomethingUsable) when dealing with DS queries/results is rather generic and could be made available for parsing, it could also be changed to return an array of objects instead of the single one i use there.

the second (updateElementsFromObject) though simple could be extended to take into consideration more complex cases in time (multi results etc.) but I believe that even as it is the average user would benefit from its simplicity.

**Comment by mikhail-vl** [comment]
@ashleymcdonald As I replied in another issue, in the latest version 3.2.0, we added automatic response parsing and it should not be required. Are you using the latest version?

  Maybe, I am missing something here.

**Comment by asimonok** [comment]
@ashleymcdonald it can be done through Dynamic Text Plugin. You can add an empty panel and in helpers just add global functions like

```
window.myFunction = () => {
//somelogin
}
```
