### ISSUE TITLE
Is the data source initial example in blog correct?

### ISSUE THREAD

**Issue by ashleymcdonald** [VolkovLabs/volkovlabs-form-panel#264]
Shouldn't the initial request custom code use the result from the database query in some way?

in our testing unless we explicitly used the items to set the element values then no initial values were set.

https://volkovlabs.io/blog/form-panel-data-source-20230908/#data-source

**Comment by mikhail-vl** [comment]
@ashleymcdonald As we demonstrated in the latest YouTube tutorial, you can choose fields for each element when using Query for Initial Request. In this case, values will be assigned automatically. For Data Source it works as well, when fields are selected.

  You can access Query data using `data` directly for specific use cases.

  We are updating documentation for the recent changes, should be live later this week: https://github.com/VolkovLabs/volkovlabs.io/pull/524
