### ISSUE TITLE
Add getTimeSrv() as timeService as global

### ISSUE THREAD

**Issue by jacksongoode** [VolkovLabs/volkovlabs-form-panel#265]
This would allow soft refreshes that just requery the panel's. This is useful in a situation where the form panel inserts new data and we don't want a full hard refresh from `locationService.reload()`. We can instead use `getTimeSrv().refreshDashboard()`.

**Comment by jacksongoode** [comment]
Realizing this might not exist in the current Grafana code base... I wonder where they moved this function?

**Comment by asimonok** [comment]
@jacksongoode we've added `context.refresh` function which refreshes the dashboard. Please let us know if it works for you
