### ISSUE TITLE
Question: Is there a way to validation form before submit?

### ISSUE THREAD

**Issue by ivan-stankov-golang** [VolkovLabs/volkovlabs-form-panel#267]
Is there a way to validation form with custom code before submit?

**Comment by mikhail-vl** [comment]
@ivan-stankov-golang Are you using Rest API? You can use custom requests to verify input and submit if it's correct.

  There was another request for form validation. And we will look into it.

**Comment by ivan-stankov-golang** [comment]
@mikhail-vl so I need to use custom code and do the validation and the http request? Thank you.

**Comment by mikhail-vl** [comment]
@ivan-stankov-golang That's the current option.

  We will look into adding validation in the future versions.
