### ISSUE TITLE
How to access data typed into string fields

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#269]
Probably missing the obvious here but I am trying to just save the values typed in to text string fields. But this code just shows empty values when console.log. So how do i access the typed values. There is no intial data request as its just a form for users to type data into

```
console.log(
  templateService
);

const Email = 'EMAIL@EMAIL.com;
console.log(Email.toUpperCase());

let url = `APIREMOVED`;

// Add body elements as headers to the URL
options.elements.forEach((element) => {
  url += `&${element.id}=${element.value}`;
  console.log(element)
});

try {
  console.log("Sending API request...");
  const response = fetch(url, {
    method: 'POST', // or 'PUT'
    headers: {
      'Content-Type': 'application/json',
    },
  });
  console.log("API response received:", response);
  notifySuccess(['Update', 'Values updated successfully.']);
  locationService.reload();
} catch (error) {
  notifyError(['Update', 'An error occured updating values.']);
  console.error(error);
}
```

**Comment by mikhail-vl** [comment]
@craftzneko It's should be `elements` instead of `options.elements`. In v3 we migrated from options to local state, we behind in documentation and working to keep it updated with the latest changes.

  Let me know if it helps.

**Comment by craftzneko** [comment]
@mikhail-vl  yep that worked great, thanks very much!
