### ISSUE TITLE
Can not get the custom code to work

### ISSUE THREAD

**Issue by Evgeny243** [VolkovLabs/volkovlabs-form-panel#270]
Hi @mikhail-vl . I have essentially no experience in JavaScript, so i would really appreciate if you can help me with the following simple task:
I use Query in Initial Request. The data is loaded from InfluxDB into element "PD".
Then I try in the Custom Code of the Initial Request to write a "new_value" string into the value of another element "Copy" using following code:

onChange(elements.map((element) => {
  return element.id === 'Copy' ? { ...element, value: 'new_value' } : element
});
console.log(data, response, initial, elements);
return;

Nothing happens. Also the console.log is not producing anything on the screen, so I am not sure how that function works. I attached a snapshot. Once this works the next step is to write the value of the "PD" element into the value of the "Copy" element.

Thanks!

<img width="1649" alt="Screen Shot 2023-10-17 at 3 30 32 PM" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/115658652/630e5b66-79dc-48e2-82c1-de9a41de566a">

**Comment by mikhail-vl** [comment]
@Evgeny243 Try `console.error() or warn()` instead of `console.log()`.

  Show me your form elements, what is the id for the 'Copy' element. Id and Label are different.

**Comment by Evgeny243** [comment]
<img width="810" alt="image" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/115658652/1663fb39-2d9b-4495-86ab-fc5a15132ca2">
<img width="806" alt="image" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/115658652/df252fe9-d890-4438-a2fc-9dbddec7f704">

**Comment by Evgeny243** [comment]
I can see the console now. Much easier to troubleshoot. The function also works now.
How should I change the code above to replace the value of "Copy" by the value of "PD"?

**Comment by mikhail-vl** [comment]
@Evgeny243 Like that:

```
const PD = elements.find((element) => element.id === "PD");
console.warn(PD.value);
```

**Comment by Evgeny243** [comment]
@mikhail-vl A followup question: When I try to write something to database using fetch I see an error: 
Blocked loading mixed active content “http://influxdb.......&precision=ms”

When I change that to https:// then I get an error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://influxdb........&precision=ms. (Reason: CORS request did not succeed). Status code: (null).

Is that something that has a known remedy?
