### ISSUE TITLE
Connecting to server: Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Evgeny243** [VolkovLabs/volkovlabs-form-panel#271]
@mikhail-vl When I try to write something to database using fetch/POST I see an error:
Blocked loading mixed active content “[http://influxdb.......&precision=ms”](http://influxdb.......xn--&precision=ms-ur6g/)

When I change that to https:// then I get an error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://influxdb........&precision=ms/. (Reason: CORS request did not succeed). Status code: (null).

Is that something that has a known remedy?
Do I need to create a server as shown in here: https://volkovlabs.io/plugins/volkovlabs-form-panel/servers/json?
FYI my grafana is located on https, and influx on http. I believe this causes the error.

**Comment by mikhail-vl** [comment]
@Evgeny243 That's correct you can't mix HTTPS and HTTP content.

  I would recommend to use Data Source to connect to InfluxDB using the latest version of the Data Manipulation panel instead of REST API.
