### ISSUE TITLE
How do i access grafana global variables

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#272]
How can i can access grafana GLOBAL variables in code. I need to access ${__user.email} not really sure how to do this, any ideas?

**Comment by craftzneko** [comment]
Went through documentation again and i dont see how this is possible @mikhail-vl any ideas?

**Comment by mikhail-vl** [comment]
@craftzneko Variables are replaced automatically in the Custom Code like that:

```
console.log('${__user.email}');
```

**Comment by craftzneko** [comment]
Thanks @mikhail-vl
