### ISSUE TITLE
Unable to update configuration database in demo.

### ISSUE THREAD

**Issue by chongyewgithub** [VolkovLabs/volkovlabs-form-panel#273]
Can't seem to replicate the demo successfully by following the instructions / video on this link.

https://volkovlabs.io/blog/form-panel-data-source-20230908/

database used : MySQL

**Comment by chongyewgithub** [comment]
Is OK, I have figured it out.

**Comment by mikhail-vl** [comment]
@chongyewgithub Great, Data Manipulation v3 introduced breaking changes related to the value updates in local state.

  Let us know if there is anything else.
