### ISSUE TITLE
Datetime width improperly calculated

### ISSUE THREAD

**Issue by steelskillet** [VolkovLabs/volkovlabs-form-panel#274]
Version: 3.2.1
Grafana version: 10.0

The required width of the datetime type seems to get improperly calculated when inside of a section. This causes the datetime picker to overlap with other sections.

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/137853626/33df4e52-3829-42bd-92c9-faf13d2a8689)

As a bonus feature it would be nice to be able to set the width of a section and the padding between sections.

**Comment by mikhail-vl** [comment]
@steelskillet Thank you for opening the issue.

  @asimonok Could you please take a look.

**Comment by asimonok** [comment]
Created a bug in Grafana - https://github.com/grafana/grafana/issues/78466

**Comment by steelskillet** [comment]
thanks for passing that over to grafana, didn't even come to mind that it might have been an issue there.

**Comment by mikhail-vl** [comment]
@steelskillet No worries, we will check with Grafana team what can be done.

**Comment by mikhail-vl** [comment]
Grafana team confirmed the issue https://github.com/grafana/grafana/issues/78466.
