### ISSUE TITLE
Add username to update request payload

### ISSUE THREAD

**Issue by gerrygralton** [VolkovLabs/volkovlabs-form-panel#275]
Is there any way to add the username of the account that made an update to the update request payload? It would be good for keeping track of who has made which change.

**Comment by mikhail-vl** [comment]
@gerrygralton There are multiple ways you can do it:

 1) Add a username in the `Custom Payload` for REST API
 2) Add a hidden element that contains a username.
 3) Use the global variable `${__user.login}` as Header Parameter.

  Let me know if it helps.
