### ISSUE TITLE
Initial select options no options fond

### ISSUE THREAD

**Issue by smarkm** [VolkovLabs/volkovlabs-form-panel#276]
Hi, I just used MySQL query result to initial the select options, but it has no options fond like this screenshot, did I go the wrong way or?
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/5517120/fc970dcc-c0a3-4941-8af2-fd8f19ea528d)

**Comment by mikhail-vl** [comment]
@smarkm Query Field is used to get the current value in the latest release.

  We have a PR to get Custom options from the query, but it's not merged yet: https://github.com/VolkovLabs/volkovlabs-form-panel/pull/254. It will be a part of the upcoming release

**Comment by smarkm** [comment]
Noted and thanks @mikhail-vl , great job
