### ISSUE TITLE
Is there a way to update the value of a dashboard variable from custom code?

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#277]
Hi,

I am using Custom Code for the Initial and Update requests. I would like to update a ${serverStatus} dashboard variable from the Custom Code. Is this possible?

Thanks,
-Ray

**Comment by mikhail-vl** [comment]
@rantinray It's described in the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-variable-after-update-request-to-interact-with-other-panels
