### ISSUE TITLE
Can the Reset button be disabled?

### ISSUE THREAD

**Issue by rantinray** [VolkovLabs/volkovlabs-form-panel#278]
It appears that the Reset button is always enabled. Could it be somehow tied to the state that drives the Submit button so that the Reset is only enabled when the local data has been modified from the initial conditions?

Thanks,
-Ray

**Comment by rantinray** [comment]
I guess a more general use case would be to be able to disable the Reset button from the code. That way it could be used for things other than Reset.

-Ray

**Comment by mikhail-vl** [comment]
@asimonok Can we implement logic similar to elements `showIf` for reset button?
