### ISSUE TITLE
Multi-statement mysql queries

### ISSUE THREAD

**Issue by steelskillet** [VolkovLabs/volkovlabs-form-panel#279]
The form I have requires data to be inserted into multiple tables on the database (mysql) during the 'Update' step. I don't believe there is currently a way to do this, but if there is that would be great.

**Comment by steelskillet** [comment]
I figured it out by just using grafana's web api and custom update request. feels a little wonky but it works for now. I also saw a PR for grafana to allow multi-statement sql queries, that may solve the problem as well.

**Comment by asimonok** [comment]
@steelskillet we don't support several queries to simplify the panel.
You can use a custom code for update request and run several quries yourself. 

```
fetch('/api/ds/query',
  method: 'POST',
  body: JSON.stringify({
    queries: [
      {
        datasourceUid: ',
        refId: 'A',
        ...payload,
      },
      // another one
    ],
  }),
)
```

Please check the swagger - https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/public/api-merged.json to see all available fields for the endpoint
