### ISSUE TITLE
Number Input fields don't allow 0 value.

### ISSUE THREAD

**Issue by Yoslandy** [VolkovLabs/volkovlabs-form-panel#280]
Hi Team.

Thanks you for your always fast response and keep going. You doing a great job.

My question this time is that I can't put 0 in Number Input field in Data Manipulation plugin. Is there any reason why that is not possible? When we using the right arrow in the field I can see how it jump from 1 to -1 but even manually I can't put 0. Also I tried saving 0 in the database for empty fields and load it after but its like the field has defined if is 0 put nothing. 

This can help for some forms where the customer not necessarily need to enter any value but wants to see the 0 value. 

Do we have any variant or option for it?

Thanks in advance

**Comment by mikhail-vl** [comment]
@Yoslandy Thank you for submitting an issue. We may have a check for 0 mishandled.

  We will check and fix it in the upcoming release.

**Comment by Yoslandy** [comment]
Thanks you @mikhail-vl Its a pleasure to use your resources and your fast response is incredible. I cant wait to see the new release. Blessings

**Comment by olindo55** [comment]
Hi team, 

I have the same issue when I want add value 0 in 'select with custom option', I can add 0 but when I do the query I have bug.

**Comment by mikhail-vl** [comment]
@asimonok Please take a look.

**Comment by Yoslandy** [comment]
Thanks so much for solve this bug. Will help a lot. I appreciate your fast response always
