### ISSUE TITLE
unable to update '0' value and custom code not working in data manipulation plugin 3.X version

### ISSUE THREAD

**Issue by vnvasireddy** [VolkovLabs/volkovlabs-form-panel#285]
hello sir,
we are using your data manipulation plugin for grafana screen configuration.
when we are working with older version 2.8 we were able to update values with custon code using url, same code when we tried in new version not able to update values.
please suggest any changes needs to be done for the below configuration.
const password = prompt("Enter password:", "");
if (password !== "xxxxxxxx") {
  notifyError(["Error", "Incorrect password. Update not allowed."]);
  return;
}

options.elements.forEach((element) => {
  const body = {};
 
  if (!options.update.updatedOnly) {
    body[element.id] = element.value;
    console.log("element.id:", element.id);
    return;

  }

  /**
   * Skip not updated elements
   */
  if (element.value === initial[element.id]) {
    return;
  }
  body[element.id] = element.value;

  /**
   * Set URL for ID 13052 with custom tag name,  id = "tagname13052"
   */
  var id = (element.id).slice(7, 12)

  
  const url1 = 'http://192.168.xx.xx:1880/endpoint/grafana'
  
  body["id"] = parseInt(id);
  body["val"] = element.value;
 
  fetch(url1, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "PRIVATE-TOKEN": "$token",
    },
    body: JSON.stringify(body),
  })
 
    .then((response) => {
      if (response && response.ok) {
        notifySuccess(["Update", "Values updated successfully"]);
        initialRequest();
      } else {
        notifyError([
          "Error",
          `An error occurred updating values: ${response ? response.status : 'Unknown'}`,
        ]);
      }
    })
    .catch((error) => {
      console.error(error);
      notifyError(["Error", "An error occurred during the request"]);
    })
});

posting the tag name and value to node-red and not able to enter '0' value before submitting. 

thanks in advance,
iplon india pvt ltd.

**Comment by mikhail-vl** [comment]
@vnvasireddy DM v3 introduced a breaking change to store values in the local state instead of options.

  Take a look at the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/#update-local-state-in-data-manipulation-panel-310

  Regarding '0', we will fix in the upcoming version.

**Comment by vnvasireddy** [comment]
Thank you so much for your quick reply...waiting for new version.

**Comment by mikhail-vl** [comment]
@vnvasireddy Zero in numbers, resolved in https://github.com/VolkovLabs/volkovlabs-form-panel/pull/288 and will a part of the upcoming release this week.

**Comment by vnvasireddy** [comment]
thank you

**Comment by vnvasireddy** [comment]
Dear mikhail,
One more suggestion needed from you regarding plugin that when there is a dashboard reload old values are set to default values but we need old values even after reload and when we try to send same value to url submit button getting disabled. So any suggestion regarding this?

**Comment by mikhail-vl** [comment]
@vnvasireddy Please open a new issue for the new question.
