### ISSUE TITLE
Add TextLink form element

### ISSUE THREAD

**Issue by tomikos** [VolkovLabs/volkovlabs-form-panel#286]
It's currently not possible to display a clickable link
Would be very nice to have it
https://github.com/grafana/grafana/tree/main/packages/grafana-ui/src/components/Link

And in general, is it possible to just support the use of any element from the [grafana-ui](https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-intro--page) in a smart dynamic way?

**Comment by mikhail-vl** [comment]
@tomikos Every element from grafana-ui is different and requires specific parameters. We can think of something, but at this point DM supports most of the required elements already.

  Regarding TextLink, what is the use case? How do you display it?

**Comment by tomikos** [comment]
@mikhail-vl think of displaying a hyperlink to another system.
When a user clicks on Submit we create a record in the DB, as part of the created record there's a link to another system that I want to disaply to the user. Right now I display it as a Read-only box which is not clickable.

**Comment by mikhail-vl** [comment]
@asimonok Can we add a new Link element?
