### ISSUE TITLE
Zero in Form Elements

### ISSUE THREAD

**Issue by olindo55** [VolkovLabs/volkovlabs-form-panel#287]
Hi everybody,

In first, Thanks for your great job !
If i want use a value 0 or 0.00... I have blank, I can't do it

Can you help me for solve this ?

BR

Olindo

**Comment by Yoslandy** [comment]
Hi Olindo,

I think Its fix already, just check this post out

https://github.com/VolkovLabs/volkovlabs-form-panel/issues/280#event-10947826760

We maybe have to wait for the next release version. Probably @mikhail-vl can confirm

Thanks

**Comment by mikhail-vl** [comment]
@Yoslandy Yes, it's fixed and will plan to release it over the weekend after ObservabilityCON.
