### ISSUE TITLE
Dashboard variable not replaced in Update request payload

### ISSUE THREAD

**Issue by aggo** [VolkovLabs/volkovlabs-form-panel#289]
I am trying to save the password of my influxdb as a dashboard variable. Then I want to use it in the code that creates the payload for the update request, like this: 
```const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "text/plain",
    "Authorization": "$token",
  },
  body: body,
})
  .catch((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });```
However, the $token never gets replaced, I also tried using `replaceVariables` but to no avail.

**Comment by mikhail-vl** [comment]
@aggo Variables in the Custom Code are replaced automatically.

  Are you sure that `token` is the correct Id for the Dashboard Variable?
  Could you double check in the Browser's Console -> Network headers for the POST requests that it was not replaced.

**Comment by clattan** [comment]
@mikhail-vl @aggo, I'm experiencing the same issue.  The dashboard variable is being replaced properly in the initial request and update request, but not in the update payload.  My variable name is pathLocator and I put console log statements to output the variable in custom code sections for the initial request, update request, and update payload.  The correct string value displays in the console from the initial request and update request sections.  The string "$pathLocator" is displayed when I execute the console log statement from the update payload custom code section.
![Dashboard Variable Replacement](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/133888296/a97ede7c-6897-4dc6-ad69-01d4a391d95b)

**Comment by mikhail-vl** [comment]
@aggo @clattan We will check and get back to you.
