### ISSUE TITLE
Implement Height coding area for Data Manipulation

### ISSUE THREAD

**Issue by Yoslandy** [VolkovLabs/volkovlabs-form-panel#290]
Hi Team. 

As a fanatic user of your plugins, I just bring a suggestion today. 

I'm using Data Manipulation plugin long time and is a little annoying the small area for coding. But I'm now using Dynamic Text plugin and seems easier to code due to I can expand the Height of the area. 

Could you implement that feature to this plugin too? Will be nice to coding better. Even can affect both, Initial Request and Update Request, I don't think its a problem having one for both.

Like this from Dynamic Text

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/34694121/0bbc738c-1927-43dc-aff2-215e960daeb8)

Thanks in advance and you always doing a great job.

**Comment by mikhail-vl** [comment]
@Yoslandy Thank you for opening feature request. I agree and like the height slider for Dynamic Text.

  We will plan to add it in the upcoming version.
