### ISSUE TITLE
going to default values after dashboard load and unable to send same value as submit button getting disabled

### ISSUE THREAD

**Issue by vnvasireddy** [VolkovLabs/volkovlabs-form-panel#293]
Dear mikhail,
suggestion needed from you regarding plugin that when there is a dashboard reload old values are set to default values but we need old values even after reload and when we try to send same value to url submit button is getting disabled. So any suggestion regarding this?

**Comment by vnvasireddy** [comment]
Dear mikhail

thanks for the new version

**Comment by mikhail-vl** [comment]
@vnvasireddy You can disabled panel synching in the upcoming version 3.4.0.

  You can try it from the CI artifact: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/6974128417
  We just released a new version and will plan to release 3.4.0 in December.
