### ISSUE TITLE
please disable initial request when dashboard load 

### ISSUE THREAD

**Issue by vnvasireddy** [VolkovLabs/volkovlabs-form-panel#300]
dear Mikhail Volkov,
As of now we are using your plugin version 2.8.0 and it is very comfortable for us.
But in that can we have one change that when dashboard reloads it should not execute initial request function or OnClick it should not perform initial request function. anything is ok.
{options.reset.variant !== ButtonVariant.HIDDEN && (
                <Button
                  className={cx(styles.margin)}
                  variant={options.reset.variant as any}
                  icon={options.reset.icon}
                  style={
                    options.reset.variant === ButtonVariant.CUSTOM
                      ? {
                          background: 'none',
                          border: 'none',
                          backgroundColor: theme.visualization.getColorByName(options.reset.backgroundColor),
                          color: theme.visualization.getColorByName(options.reset.foregroundColor),
                        }
                      : {}
                  }
                  disabled={loading}
                  onClick={initialRequest}  *** wants to disable this functionality* it should return some boolean true
                  size={options.buttonGroup.size}
                >
                  {options.reset.text}

please do the needful as it is very convenient to use this version

**Comment by mikhail-vl** [comment]
@vnvasireddy We added an option to disable synch with dashboard reload in the upcoming version.

  You can test from the CI artifact while we are working on the new version.
