### ISSUE TITLE
cannot import JS resource

### ISSUE THREAD

**Issue by zhangyi20220507** [VolkovLabs/volkovlabs-form-panel#302]
Thank you a lot for excellent job of dynamic-text panel, I really like it. 
However, when I use the latest version, I try to add an external JavaScript source, it occur below error. I don't know whether it is wrong from panel side or from my Grafana configuration side.
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/105102433/5618074f-5a54-4f10-9129-8934e68361ad)

**Comment by mikhail-vl** [comment]
@zhangyi20220507 It's a known issue with the latest release v4.2.0 of the panel in Grafana prior to 9.5.

  It's already fixed and will be a part of the upcoming release v4.3.0.
  You can upgrade to G9.5+ or G10 or use panel v4.1.0 until the next release.
