### ISSUE TITLE
Updating dashboard variables from form element code block. 

### ISSUE THREAD

**Issue by ashish-y** [VolkovLabs/volkovlabs-form-panel#304]
Hi, 

Is there any way to update the dashboard variables from the code block under form elements?

**Use case:**
I am doing some calculation based on selected values in the dropdown form element and want to set that value of a dashboard variable based on that calculation.

**Comment by ashish-y** [comment]
Thanks for the quick reply @mikhail-vl . Appreciate it!
I'll try a different approach as custom code is only triggered on initial, post and reset request and I want to dynamically update an element on change of any other element in the form.

**Comment by mikhail-vl** [comment]
@ashish-y We have a plan to add dynamic OnChange to elements in the future versions.

**Comment by craftzneko** [comment]
I just stumbled on this and i am trying to acheive something very simlar, depending on options i want to clear values from other elements, i was going to do this by storing state in a varibale and setting, but then found locationService is not defined. Is there are a better way to achieve this or is this planned update close to being released? @mikhail-vl

**Comment by mikhail-vl** [comment]
@craftzneko Please check the recent blog and video how to use `locationService`: https://volkovlabs.io/blog/form-panel-use-variables-20240301/
