### ISSUE TITLE
Default Value Display '0' Issue in Number Field in Data Manipulation Form

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#306]
I have identified an issue related to the default value display in the Number Field on forms within this plugin. Currently, when a Number Field is included in a form, it consistently displays a default value of 0, 
<img width="636" alt="Screenshot 2023-12-11 114011" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/114749992/0215524f-e61e-45ff-ae40-36407af205b4">
 how can make this number field blank by default ?

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe Did you setup fields as Number Input? It requires a number. If nothing is specified it's 0.

  You will need to use String Input to support empty default values.

**Comment by utkarshsalunkhe** [comment]
I have specified a particular field as a number field, but I'm encountering
an issue where the field displays the default value '0' in the form. Could
you please guide me on how to make this number field empty in the form by
default ?

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe Number fields always will be 0, because there is no "empty" numbers.

  As I said, to allow empty values, you will need to use String input elements: https://volkovlabs.io/plugins/volkovlabs-form-panel/form-elements/#string-input
