### ISSUE TITLE
mysql multiple SQL queries simultaneous

### ISSUE THREAD

**Issue by exx22** [VolkovLabs/volkovlabs-form-panel#311]
Hi,

Please help with creating a payload script that will simultaneously execute two SQL queries at the click of a button
SQL update: UPDATE REPORTER.REPORTER_STATUS SET acknowledged = 1 WHERE serverserial='$serverserial';

SQL insert:  INSERT INTO REPORTER.REPORTER_JOURNAL (chrono, userid, servername, serial, serverserial, text1) VALUES (NOW(), '\${__user.id}', 'GRAFANA', '$serverserial', '$serverserial', 'komentar');

Br,
M

**Comment by asimonok** [comment]
You should use datasource and custom code enabled for update payload to return correct sql query
```
return {
  rawSql: `
UPDATE REPORTER.REPORTER_STATUS SET acknowledged = 1 WHERE serverserial='$serverserial';

INSERT INTO REPORTER.REPORTER_JOURNAL (chrono, userid, servername, serial, serverserial, text1) VALUES (NOW(), '${__user.id}', 'GRAFANA', '$serverserial', '$serverserial', 'komentar');
`,
  format: 'table',
};
```

Or run /ds/query yourself in the update custom code how it's described here - https://github.com/VolkovLabs/volkovlabs-form-panel/issues/279#issuecomment-1871831061

Please let us know if it works for you
