### ISSUE TITLE
Drag and Drop for Form Elements isn't working.

### ISSUE THREAD

**Issue by Yoslandy** [VolkovLabs/volkovlabs-form-panel#312]
Hi Team.

Thank you for the great job you are doing and for the new releases.

I would like to point out that the Drag and Drop of Form elements is not working for some reason.

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/34694121/7361ba02-6979-4c71-a6cd-1617d7eb076b)
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/34694121/d29a17bc-946e-4335-9a2b-db4aefbef825)

Thanks you for your support and great responses.

Josh

**Comment by mikhail-vl** [comment]
@Yoslandy What Grafana version do you use? It was as expected for me.

**Comment by Yoslandy** [comment]
Thanks @mikhail-vl 

Im using 
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/34694121/b4268bdb-3937-46b7-aafc-3dbc78c9f204)

I know it was working before, but I dont know why stop working. If you have any idea let me know, if not, is not a big deal for now, just a bit anoying when I want to add a new element at the top of the list

Thanks again in advance

**Comment by mikhail-vl** [comment]
@Yoslandy Thank you for letting us know, just before the release :)

  It's working in 10.2.2 and broken in the 10.3.0, which is not released yet, but available in the Grafana Cloud.

  @asimonok Could you please check what changed and how we can fix it.

**Comment by Yoslandy** [comment]
Thanks you @mikhail-vl and @asimonok. Great Job!!!

I cant wait to see it and to see what are you doing for upcoming versions and plugins

Blessings

**Comment by mikhail-vl** [comment]
@Yoslandy With this issue fixed, I have one more PR to review and a release later today.

  I will submit to Grafana team to review and include in the Grafana Cloud.
