### ISSUE TITLE
Getting Missing boundary in multipart/form-data error in logs while uploading the files

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/volkovlabs-form-panel#316]
Getting Missing boundary in multipart/form-data error in logs while uploading the files.

**Comment by vanimesh** [comment]
The API works fine when i test it via postman.

**Comment by vanimesh** [comment]
Any help pls ?

**Comment by asimonok** [comment]
Duplicated by #252

**Comment by fgnn** [comment]
I think this is different than #252, or perhaps I have missed something in both issues that has already been solved.

Here is my setup
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/12035623/7fae1f04-2f1c-4903-bd89-9137207fd5e4)

And here is the message as captured in chrome
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/12035623/7507193f-1bfc-4bfe-b94b-55b2dc4660b6)

and the payload
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/12035623/bffdd3e0-3b74-4852-b402-c4670dd38563)

And then in my python flask API, it does not detect it as a form or file. Although the data is present, it is not in an easy or standard format to read.
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/12035623/0662e783-7660-4fad-ac78-af3087a97fda)

The issue looks to be that the "boundary" is not included in the Content-type, as [described here](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).

**Comment by vanimesh** [comment]
Were you able to solve this then ??

**Comment by fgnn** [comment]
@vanimesh, no I did not find a solution. 
Thanks @mikhail-vl for re-opening this.

**Comment by mikhail-vl** [comment]
@fgnn We appreciate your questions and working on an article and updating documentation to highlight latest updates.

**Comment by vanimesh** [comment]
Hi @asimonok , thank you for working upon the request. Any idea when we could have this fix released ?

**Comment by mikhail-vl** [comment]
@vanimesh PR is merged. You can try the updated version from CI artifacts.

**Comment by fgnn** [comment]
Updated to 3.7.0 and confirmed it works now. Thanks!

**Comment by mikhail-vl** [comment]
@fgnn Thank you for confirming.

  Please let us know if there is anything else.

**Comment by vanimesh** [comment]
Yess it works fine for me too. Thank you very much
