### ISSUE TITLE
multivalue variable gives value with curly brackets

### ISSUE THREAD

**Issue by qczak** [VolkovLabs/volkovlabs-form-panel#317]
I have a problem using variable when 'ALL' value is being used. Using MySQL in Update Request Payload variable gives value with curly brackets which generates error in request.  
I have rather poor programming skills and can't solve this problem.  

I know I can solve this by using reaping panels option but I want to avoid that.

**Comment by mikhail-vl** [comment]
@qczak We just merged PR, which replaced dashboard variables in the payload.

  It's a part of the today's release.
