### ISSUE TITLE
More problems with zeros

### ISSUE THREAD

**Issue by paustin01** [VolkovLabs/volkovlabs-form-panel#319]
Hi there, I've set up a simple example exactly like the video with a couple of form elements to read and then update values in a postgres table. My issue is that updating a value to anything (but a zero) works fine but if zero is the value it's a **no-op**. I'm running 3.4.0 of the plugin in self-hosted (docker) Grafana 10.2.2.

In my example below you can see how I'm updating two fields. The first is being changed from 1 to 0, and the second is being changed from 1 to 2. You can see that the 2 worked but the 0 did not. Printing out the query generated seemed to indicate that the zero was essentially being ignored and the value in the query was still 1. Any ideas?

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/780060/b01aacff-bd13-4903-a0cb-670dc3735543)
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/780060/1ece65a9-1e18-4e56-b2fe-fa541e124477)

**Comment by asimonok** [comment]
@paustin01 It should be working. Could you share your panel config? Item value can be updated in custome code or somewhere else

**Comment by mikhail-vl** [comment]
@paustin01 I just double-checking on the upcoming v3.5.0 and it works as expected.

  Please let us know if there is anything else.

**Comment by paustin01** [comment]
Sorry for the delay. Holidays. I'll give the new version a shot and reopen if able to repro.

**Comment by paustin01** [comment]
If it's at all helpful, I'm running 3.4.0 and was just doing a simple insert statement into a PG database. Works fine if the value is anything but zero but if it is zero I get the following. (I'll try again when 3.5.0 drops too)

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/780060/506eef6f-2091-4d1f-af8d-a0c4eb557711)

**Comment by sadashiva8** [comment]
The same issue in Radio Group with Boolen options field when choosing False value, with True value it's working ok. Have tried both INSERT/UPDATE postgres requests, same issue with 'false'.  Version 3.4.0
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/117537035/bff12132-91df-4652-baff-1cd674aeaf9d)

**Comment by mikhail-vl** [comment]
@paustin01 @sadashiva8 Thank you for raising the issue. We are investigating.

**Comment by asimonok** [comment]
@paustin01 @sadashiva8 please share your panel config to repduce the issue

**Comment by asimonok** [comment]
Please check if you use something like that in get payload code

```
const payload = {};

elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
})

/**
 * Data Source payload
 */ 
return {
  rawSql: // sql,
  format: 'table',
};`;
```

if it's true, you should change checking of element.value to
```
if (element.value === undefined) {
  return;
}
```

**Comment by sadashiva8** [comment]
This works! Great, thank you very much for your support. 👍 
Changed:
if (!element.value) {
    return;
  }

To: 
if (element.value === undefined) {
  return;
}

**Comment by mikhail-vl** [comment]
@paustin01 Let us know if you have the same issue and proposed code works for you?
