### ISSUE TITLE
file upload to datasource with custom code

### ISSUE THREAD

**Issue by pagules** [VolkovLabs/volkovlabs-form-panel#320]
I have recently discovered the data manupiulation panel and  I'm very impressed about the abitlity of writing data directly to a datasource. Would it be possible to write file content base64  encoded (e.g. *.pdf douments) to a datasource directly from custom code. I didn't find any infomation in the documentation or code examples.  It would be great if someone could give me some support to make it work.

**Comment by mikhail-vl** [comment]
@pagules Thank you for opening the issue.

  We will add an example in the upcoming blog post.

**Comment by pagules** [comment]
this is good news , I will watch the blog post entries for further information
