### ISSUE TITLE
Change "Choose" to the current database value for a field using the "Select with custom options"

### ISSUE THREAD

**Issue by mdoakes42** [VolkovLabs/volkovlabs-form-panel#329]
As a database person this is a great addition to Grafana.  Thanks for your work on this. Love it so far! 

Is it possible to keep the current database value instead of "Choose" when using the Select with custom options.  (Either query or options).   It would be nice to know what the current value is without having to use 2 sections to show "Current/New"

It looks like you sort of do that when using the Radio Group with custom options by "highlighting" the value.  (Although it would be nice also if that value was "first". 

Thank you!

**Comment by mdoakes42** [comment]
Sorry, Looks like I had a user error here.. In playing around with some of the options I accidentally got rid of the "query field" mapping.. Once I put that back, It did put the current value first.  Thanks again!  Can close ticket!

**Comment by mikhail-vl** [comment]
@mdoakes42 You got it!

  Let us know if there is anything else.
