### ISSUE TITLE
ReferenceError: replaceVariables is not defined

### ISSUE THREAD

**Issue by imbence** [VolkovLabs/volkovlabs-form-panel#330]
Hi,
I am trying to use dashboard variables within my JavaScript code in the "Create Payload" - "Custom code" section and I am getting replaceVariables is not defined error.
Is there any way to do this, or it will only work in the "Form elements" section when adding it to "Show if returned value is true" code?
<img width="289" alt="image" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/22945395/f921ee35-55d7-4352-9a90-4fd090697888">
Data Manipulation Plugin Version 3.4.0
Thank you!

**Comment by mikhail-vl** [comment]
@imbence Variables are replaced automatically in the 3.4.0: https://github.com/VolkovLabs/volkovlabs-form-panel/blob/main/CHANGELOG.md

  We are working on a blog post with the latest updates. Should be ready later today or tomorrow.
