### ISSUE TITLE
how to save updated element on dashboard even after dashboard load

### ISSUE THREAD

**Issue by vnvasireddy** [VolkovLabs/volkovlabs-form-panel#335]
hello Mikhail,

tried with new version released 3.5.0 with dashboard sync option. But still after dashboard reload all dashboard updated elements are going to default values.

Please provide a suggestion for updated element to show on dashboard as it is, so that our customers will have idea of previously set dashboard value. Here, we are not using any database to store the values, so we need an option of saving dashboard   

Thanks in advance.

**Comment by asimonok** [comment]
@vnvasireddy you can use `context.panel.onOptionsChange` in the `Element Value Changed` code. Also you need to save dashboard after all initial values are set in the panel.

<img width="885" alt="Screenshot 2024-02-28 at 14 07 02" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/5b4f8f5f-4df5-4b55-acb4-a3641ffab2ef">

```
context.panel.onOptionsChange({
  ...context.panel.options,
  elements: context.panel.elements,
});
```

Please let us know if there is anything else

**Comment by vnvasireddy** [comment]
Thank you its working
