### ISSUE TITLE
Variable substitution not working in panel query

### ISSUE THREAD

**Issue by tanmay-cybersec** [VolkovLabs/volkovlabs-form-panel#336]
I am encountering an issue with variable substitution in Grafana when using the panel query feature. I have set up a variable panel within my Grafana dashboard and defined a variable that lists multiple devices. This variable is named device and correctly shows four device options in the drop-down menu.

When I attempt to use this variable in a SQL query to dynamically filter results based on the selected device, the query fails with a syntax error. Here is the query that is causing issues:
SELECT min, max, speed FROM configuration WHERE name = '$device';

The expectation is that $device should be replaced with the actual value selected from the variable dropdown. However, this does not seem to happen, and the query execution results in an error.

In contrast, when I replace the variable with a hardcoded value, such as in the query below, the query executes successfully and returns the expected results:
SELECT min, max, speed FROM configuration WHERE name = 'device1';

From the above behavior, it's clear that the variable $device is not being substituted as expected in the panel query. This functionality is critical for allowing dynamic queries based on user selection and is a feature documented in Grafana's variable support.

Any assistance or guidance on how to resolve this issue would be greatly appreciated. If there are additional logs or debugging information needed, please let me know, and I will provide them.

Attached is a screenshot of the issue.
![0](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/119145546/3f7a16fe-d2a7-4268-bb07-fb654fa2654a)
![1](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/119145546/dba2ecfa-9b35-475e-9475-ed89feaec90b)
![2](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/119145546/343ba831-53ef-4bc0-bf10-244be1397a08)

**Comment by mikhail-vl** [comment]
@tanmay-cybersec Based on the screenshot, you have multi-selection for the variable, which most probably return an array, not a string.

  For the array you need to use `where name in ($device)`. Try to remove multi-selection for the variable if you need only a single value.

**Comment by mikhail-vl** [comment]
@tanmay-cybersec Great! Let us know if there is anything else.
