### ISSUE TITLE
Date time setting current insted of query

### ISSUE THREAD

**Issue by miguelmcmc** [VolkovLabs/volkovlabs-form-panel#337]
Im using plugin since version 3.2.1 where date and time type is working correctly.
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/36224404/71da3ced-bc4a-496e-a309-aefdaf0387a1)

After update to newest version 3.5.0 date and time prints current time instead of query data and sends 0 on update.
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/36224404/effbb63b-bceb-4d28-ba8b-9857e11bb1b4)
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/36224404/b967a111-4274-404f-b6fb-e18c7ad234b8)

Thank you.

**Comment by asimonok** [comment]
@miguelmcmc do you have a sync option enabled, right? Then, it should be fixed in the upcoming release.

Please let us know if the issue will still appear with the updated version.
