### ISSUE TITLE
Grafana API Integration

### ISSUE THREAD

**Issue by kirillyu** [VolkovLabs/volkovlabs-form-panel#340]
I can't figure it out on my own.  I want to make a drop-down list of alerts inside a form so that I can select several of them and submit the form.  Is it possible to somehow integrate the two solutions?

**Comment by asimonok** [comment]
@kirillyu you should configure a panel query which returns alerts and use it for select options. 

Panel data
<img width="837" alt="Screenshot 2024-02-27 at 13 24 20" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/dd690dc4-1f55-4024-8153-a77cd6224c11">

Initial request settings
<img width="498" alt="Screenshot 2024-02-27 at 13 43 21" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/a8306e2e-44b3-4544-b99e-6dee743edf07">

Select settings
<img width="494" alt="Screenshot 2024-02-27 at 13 45 31" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/dc7b3e58-aa67-4437-bb47-0a21376ad73c">

We are preparing a blog post with detailed steps how to use options from panel data.
Please let us know if there is anything else

**Comment by kirillyu** [comment]
wow, awesome
