### ISSUE TITLE
Update request Error when using API Data Source as Update Action

### ISSUE THREAD

**Issue by inemov** [VolkovLabs/volkovlabs-form-panel#343]
The error comes when update request is sent from the panel, and it seems returned by the grafana server, not by remote (datasource) server. Below is the error text. **Bold** shown customized payload.

Request
{"status":500,"statusText":"Internal Server Error","data":{"message":"Query data error","traceID":"00000000000000000000000000000000"},"config":{"method":"POST","url":"api/ds/query","data":{"queries":[{"datasourceId":2,"refId":"A","databaseName":**"xxxx","tagId":"HS-201","metric":"MV","value":1**}]},"retry":0,"headers":{"X-Grafana-Org-Id":1},"hideFromInspector":false}}

This is Update Request configuration:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/24581566/b78031b6-1ffa-459e-845b-ceb222146ed7)

This is Request Payload with "Code" option selected:
```
const payload = {};

elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
})

/**
 * Data Source payload
 */
return {
  "databaseName": "xxxx",
  "tagId": "HS-201",
  "metric": "MV",
  "value": Number(payload.switch),
};
```

This is request headers:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/24581566/92909de7-a4f5-49a9-895f-161dc4ff988f)

This is request payload:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/24581566/20df9226-3b27-4e19-8d4d-e12d10fbec24)

This is response:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/24581566/9ed516b1-4b58-4d42-9b24-7435e01076c7)

**Comment by asimonok** [comment]
@inemov the problem with the data source. Currently, the panel supports only backend data sources (which query data through the `POST /ds/query`). 

We will add a supporting of frontend data sources in the near future.

As a workaround, you can use custom code for update request
<img width="520" alt="Screenshot 2024-02-09 at 16 00 19" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/aabef9b0-3b2f-4dfc-ac08-bd3217071d7c">

```
const update = async () => {
  const payload = {};

  elements.forEach((element) => {
    if (!element.value) {
      return;
    }

    payload[element.id] = element.value;
  })

  context.grafana.backendService.post('your request')
};

return update();
```

**Comment by inemov** [comment]
Hi @asimonok. Thanks for your investigation! 
Glad to hear there is plan to add the feature. Although update request via code is a good temporary workaround, registered datasource has advantage of keeping authentication hidden and credentials safe.
