### ISSUE TITLE
Rest api and passing elements to the request

### ISSUE THREAD

**Issue by Casillas0905** [VolkovLabs/volkovlabs-form-panel#345]
HI
I've been looking your data manipulation plugin and I have two main questions that i did not found in the documentation, the first one is that i want to make a patch request to my own api and i did not find a way to have dynamic values so i enter a string and then that string from the form element I can put it inside the request depending what I enter, and the other thats almost the same question is how can i bind the values to the form element to my request, i saw i can do it with query field but i don't have that option. I foy can help me it would be nice 
Either way, thanks for the plugin and i hope to get an answer

**Comment by Casillas0905** [comment]
Or also is there a way to do it directly to a database?

**Comment by asimonok** [comment]
@Casillas0905 form elements will be transformed to a data object `{ [elementId]: elementValue }` which will be sent to the configured endpoint. You have to setup update request and update request payload with the settings on the screenshot (url should be yours) 

<img width="722" alt="Screenshot 2024-02-28 at 14 38 08" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/bf7975ac-1427-45c3-9bd5-ec7bb03ff6df">

Please check if update request is configured and then it should be working
