### ISSUE TITLE
Calling initialRequest() Within Form Events

### ISSUE THREAD

**Issue by the-jaluxe** [VolkovLabs/volkovlabs-form-panel#346]
I wanted to add functionality to my Grafana Form Panel where if a certain option is selected, then it will fill out the rest of the form with that information. For example, if a selected team is Windows, then I want to show the data for that team. I have custom code in my inital request payload that will automatically fetch the data based on which options are selected and it works but only if the user clicks the 'Submit' button to refresh the form from the initial request. Is there a way to call it form the Form Events option? I tried doing it this way but it ended up in an error saying that function doesn't exist.

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/55119225/733f8441-3833-4669-be03-287e89c2d8f0)

**Comment by asimonok** [comment]
@the-jaluxe thanks for the opening the issue. We will add initialRequest for the Element Value Changed code
