### ISSUE TITLE
[Q] highlight current value in "radio group with custom options" panel

### ISSUE THREAD

**Issue by mschweig** [VolkovLabs/volkovlabs-form-panel#347]
Hi, 

is it possible that the current value (e.g. on or off) is highlighted/selected in the Form Panel? So that the "current values" and "new values" approach is not needed? 

<img width="830" alt="image" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/58733365/759f0104-fcae-4c2f-a600-ab44286c34ac">

Thanks. 
Best regards, 
Manuel

**Comment by asimonok** [comment]
@mschweig you should setup an initial values query which will return all current values then current values will be highlighted

Initial values query
<img width="834" alt="Screenshot 2024-02-27 at 13 38 19" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/f3d4bd3b-141e-491f-ac36-aa51f19c5aa2">
 
Initial request
<img width="498" alt="Screenshot 2024-02-27 at 13 43 21" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/22258ef5-cb9d-4c5f-b72d-2c815e44cbc3">

Set query field for elements
<img width="494" alt="Screenshot 2024-02-27 at 13 45 31" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/ed5ed44b-16f0-447d-82f9-4f261a6aac4d">

We are preparing a blog post with detailed steps how to accomplish it. Please follow on updates
