### ISSUE TITLE
Events in Grafana

### ISSUE THREAD

**Issue by BlinderMiri** [VolkovLabs/volkovlabs-form-panel#348]
I'm working with a geomap panel in grafana with a geojason layer that shows me some areas. In addition I have a variable called AOI (area of interest). I'm trying to add an on-click event that when an area is clicked, it will be colored in a black frame and the variable AOI will be updated to the value of that area.
My question is, is there any concept of events in Grafana? If so, how do you use them?
If not, how do I add javascript code to grafna to do this?

**Comment by mikhail-vl** [comment]
@BlinderMiri For inter panel communication you can use `EventBus` which support from v3.4.0: https://volkovlabs.io/blog/form-panel-3.4.0-20240105/#event-bus-and-app-events
