### ISSUE TITLE
Add input type time

### ISSUE THREAD

**Issue by abrahammarco7** [VolkovLabs/volkovlabs-form-panel#351]
Hello, first of all I wanted to congratulate you for the great work you have done. Regarding the question I wanted to ask you, I have not seen any input type time, yes it is true that you have a input type datetime and from this I can obtain only the time, but it is not the same, the question is if you are considering including it in a future.

**Comment by mikhail-vl** [comment]
@abrahammarco7 Thank you for submitting feature request. We will look into adding time type.
