### ISSUE TITLE
Select nested values based on the selection

### ISSUE THREAD

**Issue by abrahammarco7** [VolkovLabs/volkovlabs-form-panel#352]
Hello, I needed to make nested select, so that depending on the option the user chooses in the first select that is filled with a query to the database, the second select is filled with another query to the database. I don't know how to obtain the result of the selection of the first select and use it in a variable for the query of the second select, I have tried to do it by adding the id of the first select to the second query, without obtaining results. I haven't seen anything similar in the documentation, I wonder if you can tell me if you have this documented somewhere or an example. Thank you so much. All the best.

**Comment by asimonok** [comment]
@abrahammarco7 we are preparing a blog post how to accomplish it. Please follow on the updates
