### ISSUE TITLE
Get géolocalisation of th user as variable to insert in database

### ISSUE THREAD

**Issue by coutouly** [VolkovLabs/volkovlabs-form-panel#354]
Is it possible to add to your plugin the possibility to have the geolocation of the user of grafana like a variable :
$_user.email
$_ user.geolocation 
Or $_location
With latitude and longitude
What do you think of this?
Thanks in advence

**Comment by asimonok** [comment]
@coutouly you can use any of available user parameters from `window.grafanaBootData.user`. Geolocation requires user allowed it which is not a part of the plugin functionality.

Please let us know if there is anything else
