### ISSUE TITLE
Is my use case suitable?

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#359]
Looking to see if my use case fits in. I want to create a form that will alter the queries used for other panels on the dashboard either directly or just refresh the other panels. The form will contain some elements that can be used to alter the data SQL query such as filtering. Even possibly allowing custom SQL code to be passed through. Is this possible or am i going to run into problems trying to implement this.

for example my form might have

Assetname ........h787gj
Return Rows.......2

When submitted it would then alter a table panel to show that query with the applied filters.

**Comment by vitPinchuk** [comment]
Hi @craftzneko 
You can use our Business Variable Panel plugin to achieve your goal. Or we have a great blog article [Synchronizing Dashboard Variables with Data Manipulation Dashboard](https://volkovlabs.io/blog/form-panel-use-variables-20240301/), it should help you solve the problem
