### ISSUE TITLE
Monaco code editor Psql language

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#363]
Is it possible to add custom code syntax to monaco code element. I am sepcifically looking for PostgreSQL syntax as i have craeted a custom search box for users to type code into that will search. Cheers

**Comment by mikhail-vl** [comment]
@craftzneko It's a good idea. We will look into it and implement in the future versions.

**Comment by craftzneko** [comment]
Too late now I guess but in the future if you get the chance to add more, Powershell syntax would be hugely helpful for our use cases in the code editor as well @mikhail-vl  :-)

**Comment by mikhail-vl** [comment]
@craftzneko Next time then. This is what we have so far:

```
export const enum CodeLanguage {
  C = 'c',
  CPP = 'cpp',
  CSHARP = 'csharp',
  GO = 'go',
  JAVA = 'java',
  JAVASCRIPT = 'javascript',
  JSON = 'json',
  MYSQL = 'mysql',
  PHP = 'php',
  PGSQL = 'pgsql',
  PYTHON = 'python',
  RUBY = 'ruby',
  SQL = 'sql',
  TYPESCRIPT = 'typescript',
}
```
