### ISSUE TITLE
Radio group and code dont appear to have hide or unhide properties

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#364]
this is such a useful feature to enable dynamic form rendering based on users prior options without this i cant use these advanced  elements. Can this element be added or is there a way to hide them? I am working around it by setting width to zero but it just looks terrible. Tried also using disabled which also doesnt seem to work

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/662108/b9521e8c-7086-42ba-acce-8ff69182a8d8)

**Comment by craftzneko** [comment]
I just realised there is code to display if true and false. So used that but is there supposed to be hidden and disabled usable?

**Comment by mikhail-vl** [comment]
@craftzneko ShowIf using code and hidden are two different functionality:
 - ShowIf was introduced for dynamic forms, which depends on dashboard variables, and skip elements which are not required.
 - Hidden for String elements was introduced for sending data not visible to the users.
