### ISSUE TITLE
Search greyed out

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#366]
I have a form that sets some grafana variables and then the data source refreshes based on those variables. I have also set a reset code to run in Reset to clear the form and clear the grafana variables which does seem to work, but then if i type in the same search parameters the search button is greyed out almost as if the local state remembers its fetched that data. Have i missed something here

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/662108/47c13605-2665-43c2-a0b5-4075032ceda8)

**Comment by mikhail-vl** [comment]
@craftzneko Please check the latest video and blog post, which explains how to work and synchronize data manipulation panel with dashboard variables: https://www.youtube.com/watch?v=DW-yuSopejY

Blog post: https://volkovlabs.io/blog/form-panel-use-variables-20240301/
