### ISSUE TITLE
Remove existing rows from a table

### ISSUE THREAD

**Issue by munnik** [VolkovLabs/volkovlabs-form-panel#371]
I would like to give my users an option to remove existing rows from a table. Is it possible to use this plugin to show existing rows as a table and add a trash can icon to each row in the table? The trash can should invoke an action that removes the corresponding row. Because my rows use a composite primary key, it is hard for users to enter that key in one or more fields without making mistakes.

**Comment by mikhail-vl** [comment]
@munnik You can use datalinks in the table to set the dashboard variable. Then Data Manipulation panel can use the Initial Request to retrieve the selected row using dashboard variables from the data source. To update row you can use data source or REST API.

Data Manipulation works with forms, not the table. You can create a table with buttons using Dynamic Text panel.
