### ISSUE TITLE
Panel "Submit" halts and raises "Uncaught (in promise)"

### ISSUE THREAD

**Issue by RobbinDG** [VolkovLabs/volkovlabs-form-panel#376]
I've been successfully using this panel in Grafana Cloud for a few months. Yesterday, however, the panel suddenly stopped working. In the firefox console, I notice an "Uncaught (in promise)". I have not changed the panels or dashboard in a few months.

To reproduce:
1. Take a previously functioning panel.
2. Make a change. (so the submit button is enabled)
3. Click submit.
4. See the spinner on the submit button rotate (without end).
5. Check console (F12)
6. Observe "Uncaught (in promise)"

Below is a screenshot of the error:
![DeepinScreenshot_select-area_20240314093256](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/32838181/70231c96-8c72-4b10-882c-63c0d8a97be6)

System:
OS: Arch Linux x86_64 (most recent)
Browser: Firefox 123.0.1 (64-bit)
Plugin version: most recent available to Grafana Cloud

Panel settings altered from default:
- Initial request -> Synchronize with data: Enabled
- Initial request -> Initial action: Query (with custom code that worked before)
- Update request payload -> Request payload: Code
- Update request payload -> Custom payload: changed, but worked before

Given that this happened without my intervention, I'm assuming the issue is with the plugin backend. I hadn't updated the plugin to the most recent version when I first encountered it, but after updating the issue persists. Hopefully I have provided you with sufficient information to help remedy this. If I need to change my own code in any way, I'm happy to do so. I'm afraid I cannot contribute to the project myself, I'm not a JS developer.

Thanks in Advance!

**Comment by asimonok** [comment]
@RobbinDG thanks for the submitting the issue. Could you provide more details regarding to the issue: panel config, dashboard json would be the best?

**Comment by RobbinDG** [comment]
@asimonok I tried again today and it appeared to work as before. I am unsure what could have caused the problem in the first place; I had excluded any other option before posting the issue. Sorry for the inconvenience and thanks for your swift response!

**Comment by mikhail-vl** [comment]
@RobbinDG Thank you for letting us know.

  Please let us know if there is anything else.
