### ISSUE TITLE
Question: Http POST very slow, take too much time

### ISSUE THREAD

**Issue by uid01089** [VolkovLabs/volkovlabs-form-panel#377]
Starting a bash on the GRAFANA container and running something like
 
`curl -X POST http://10.10.10.10:8099/api/store -H 'Content-Type: application/json' -d '{"topic":"ttttest", "value":"test"}'`
 
works as expected.
Let it POST out from Grafana GUI fired by a button, it tooks up to 10s. I do not find the reasons, what might cause that a high delay.

Did someone also faced this issue and how this issue can be improved.

Thanks a lot in advance.

**Comment by mikhail-vl** [comment]
@uid01089 Are you running `curl` from your laptop/pc, the one you are using to connect to Grafana?

  Data Manipulation form execute POST request from the browser, which may cause delay compare to the host you are running the command.
