### ISSUE TITLE
Add new element MultiSelect list

### ISSUE THREAD

**Issue by abogdanov37** [VolkovLabs/volkovlabs-form-panel#378]
Hello, first of all I wanted to say THANKS for that great component. Regarding the question I need a component MultiSelect List. That component used in another great component named Variable panel 
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15830587/5c56aaf6-a2da-4803-b7a4-cce6ce57b91d)
.

**Comment by mikhail-vl** [comment]
@abogdanov37 Thank you for opening feature request.

  We will look into extending Select functionality to support multi values in the upcoming version.

**Comment by abogdanov37** [comment]
@mikhail-vl Thank you. I'll wait it. If I can help some how let me know!

**Comment by vitPinchuk** [comment]
Hi, @abogdanov37 
We already have Multi-select with custom options.(from [3.1.0](https://volkovlabs.io/blog/form-panel-3.1.0-20230823/))
[Documentation Link](https://volkovlabs.io/plugins/volkovlabs-form-panel/form-elements/#multi-select-with-custom-options)  
If you need multiselect functionality you can use Multi-select element.
Or, Do you need a new element with multi-select functionality and checkboxes (as shown in the screenshot) ?

**Comment by abogdanov37** [comment]
Hi @vitPinchuk. The last option. I need a list with checkboxes as shown in the screenshot.
