### ISSUE TITLE
"Update Request Payload"  code selection can just return a string?

### ISSUE THREAD

**Issue by gooker** [VolkovLabs/volkovlabs-form-panel#381]
I just wanted to form a string and submit it as a body,
 but I saw that it seemed like the payload came out with JSON, even though I chose text in the Update Request

May I ask how to handle it

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/5688076/01a87088-2b7d-4e6d-8f77-d234f0f04f54)

**Comment by mikhail-vl** [comment]
@gooker Returned object should be in the Grafana format which any data source understands. It's not something we control.

  Take a look at the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/data-flow/#update-request

**Comment by gooker** [comment]
> @gooker Returned object should be in the Grafana format which any data source understands. It's not something we control.
> 
> Take a look at the documentation: https://volkovlabs.io/plugins/volkovlabs-form-panel/data-flow/#update-request

can i modify the payload data before submit?

**Comment by mikhail-vl** [comment]
@gooker You create your own payload in this function, but it should be in the correct format of the data source as explained in our videos and blog posts.

  Take a look at our latest video it explained how we created the Update Payload: https://www.youtube.com/watch?v=V4Sza0uDQNs&t=86s

  Let me know if it's still not clear.

**Comment by gooker** [comment]
@mikhail-vl  Thank you for the very informative video.

**Comment by mikhail-vl** [comment]
@gooker Glad it helped!
