### ISSUE TITLE
Unable to give same value after dashboard save

### ISSUE THREAD

**Issue by vnvasireddy** [VolkovLabs/volkovlabs-form-panel#384]
when a value is submitted and saved in dashboard. Same value cannot be able to give next time until there is change in value.
**Submit** button getting disabled

Any suggestion 

Thanks in advance
vani

**Comment by mikhail-vl** [comment]
@vnvasireddy We introduced additional methods and logic to enable submit button.

  Please check the blog post for details: https://volkovlabs.io/blog/form-panel-use-variables-20240301/#step-5-enable-submit-button

**Comment by vnvasireddy** [comment]
thank you its working...
