### ISSUE TITLE
`ElementDateEditor` cyclically transforms non UTC dates to UTC on every onChange()

### ISSUE THREAD

**Issue by vbackeberg** [VolkovLabs/volkovlabs-form-panel#394]
I believe there is an issue with the [onChange() code](https://github.com/VolkovLabs/volkovlabs-form-panel/blob/2869fe4735cf450b6a2f3bc40713097ccc00aea0/src/components/ElementDateEditor/ElementDateEditor.tsx#L49l) in `ElementDateEditor`. If the browser timezone is not UTC, it will repeatedly change the timezone to UTC if you click the element.

**Expected:**
In the "Date and Time" element, after selecting the date field, deselecting it and then selecting it again, it will not change.

**Observed:**
In the "Date and Time" element, after selecting the date field, deselecting it and then selecting it again, it will transform the timezone to UTC once more.

**Steps to reproduce:**
1. Set any timezone except UTC
2. Add "Date and Time" form element and apply.
3. Select a date
4. Click outside the field to trigger `onChange()`

**Fix:**
Add timezone to the input date before calling `toISOString()`

**Comment by mikhail-vl** [comment]
@vbackeberg Thank you for submitting the issue. We will look into it and get back to you.
