### ISSUE TITLE
Auto showing data triggered after choose value of payload

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/volkovlabs-form-panel#395]
Hi VolkovLabs Team,

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/81866625/111b172b-4264-4318-b02f-582815989372)

i'm new to using this plugin. i would like to edit my data after selecting the NIM Label value and then the Nama Mahasiswa Label automatically to display the data and I can edit it. is it possible to do this? if yes, please guide me.

Thank you.

**Comment by mikhail-vl** [comment]
@itsnull12, you can use dashboard variables for the selection. Check out the recent blog how we did that: https://volkovlabs.io/blog/form-panel-use-variables-20240301/
