### ISSUE TITLE
conditional panel load

### ISSUE THREAD

**Issue by iculda** [VolkovLabs/volkovlabs-form-panel#396]
Hello,
I have this scenario in which i need to trigger a remote job via api. That api returns a job id
I have  a subsequent call that check that checks again another api endpoint using the previous run id to see if the job is still running or finished
This api will return "running" or "finished"
And at the end another call to the same api but different endpoint to get the data of the job from the first call
Would data manipulation panel be suitable to be able to recheck when job finished  using second call and and only after reload panel with the results
If so how the approach should be
I tried the approach with variables but since there are no dependency between calls and api always return running or finished i was not able to make it work
Thank you

**Comment by vitPinchuk** [comment]
Hi, @iculda 
If you need to make a query only after “finished” is returned to you and you need to track the result of a query that returns “finished” or “running”  

1) you can set auto refresh for dashboard. If that works for you and does not negatively affect the rest panels of the dashboard.
In the panel in `Initial request` -> `Synchronize with data ` set “enabled”. In this case, you can write a function and your logic in the `Initial request` -> `Custom Code` section. The code will execute and return data every time the dashboard is updated
  
2) Under `Initial request` -> `Custom Code`.Write the necessary functions that will run the requests. Additionally add logic that will check api with return “running” or “finished”.  If it returns `running` then re-execute the request after a time (setTimeout).

Thank you
