### ISSUE TITLE
How to set default values for a drop down when the element is not visible yet?

### ISSUE THREAD

**Issue by ashish-y** [VolkovLabs/volkovlabs-form-panel#400]
Example: 

2 elements
**_element_1_**
**_element_2_**

**_element_2_** is only visible when **_element_1_** is set to "show" using

    const select = elements.find((element) => element.id === 'element_1');
    if (select.value.includes('show')) {
          return true
    }

How to set default value of element_2? As the element is not visible initially the initial request won't work. 
Any pointers?

**Comment by vitPinchuk** [comment]
Hi, @ashish-y.
I created two dropdowns as example
1st:  

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/6b605d4e-53da-42c0-a484-eaad789943fe)
2nd:    
  

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/9e7116b6-0e55-4279-ba3d-6ca9d1fc8e03)

and add to initial request some logic  
  

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/c9e68e9f-50db-4094-957f-3530a4224f07)
  
  
```javascript
  if (response && response.ok) {
  elements.forEach(element => {
    if (element.id === "DropDown1") {
      element.value = element.options[2].value
    }

    if (element.id === "DropDown2") {
      element.value = element.options[1].value
    }
  }

  )
}
```
After that, when I change the value in 1 dropdown “show”, I see the pre-selected value on the second one
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/8252f87c-fccd-4d2e-88ca-b22c1ba1e6a3)

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/ed72205e-8ed8-4738-b607-37a5a1de8955)

I guess the solution with еhe initial request works.

I think this is what will help you with your issue. Let us know if you have any questions
thanks
