### ISSUE TITLE
When defining show if true, dashboard crashes

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-form-panel#408]
I have a a lot of elements and i find that the dashbaord tries to evalute the section "show if true" before i have even finished typing causing a JS crash. This means i often end up having to type the code outside of the window first and then pasting in. Is there a way it could not evaluate the code or at least not cause a crash and lose the entire changes made?

Also i am not sure how to recover my dashbaord now, everytime it loads it goes into a crash loop, also not sure if this is a grafana error but after a crash, any defined variables on the dashboard are lost and i have to recreate them again

**Comment by vitPinchuk** [comment]
Hi @craftzneko 
Could you please share more details (video)
“Show if true” should apply code to onBlur changes + timeout

**Comment by craftzneko** [comment]
Here is a video showing the issue. The problem is that when you click off that section it auto saves. There are many reasons why you might want to move away from there before the code is typed for example i might need to take a teams call on my device so i click answer and as it loses focus it attempts a save and then leaves the dashboard in an unrecoverable state, needed to restore back to a previous version or lose all the code you may have typed in that session. Additionally this may be a grafana issue but all dashbaord variables are then also lost

Uploading Media1.mp4…
