### ISSUE TITLE
Data Manipulation Plugin, Select With Custom Options. Options not getting selected.

### ISSUE THREAD

**Issue by IHopeThisIsNotPermanent** [VolkovLabs/volkovlabs-form-panel#412]
# The Issue

When using the Data Manipulation Plugin, and the form element type "Select With Custom Options", The options appear in the drop down box, though when clicked, do not actually get selected. The screenshot provided shows an example, the dashboard only has one panel, there is only one form element, and it's the one in the screenshot. No other changes have been made to the visualization.

# Details

#### Grafana Version

Grafana 10.4.2

#### Plugins

. Business Variable 3.0.0
. Data Manipulation 3.7.0

#### Screenshot
![Issue](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/51992820/1b316a12-12b6-4c71-a4de-7d6244ec6cce)

**Comment by vitPinchuk** [comment]
Hi, @IHopeThisIsNotPermanent 
Use `return [{ label: "Option 1", value: "Option 1" }, { label: "Option 2", value: "Option 2" }]` it should work

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/91f994ac-7c6e-47f4-8dea-e8b61c2f1384)
