### ISSUE TITLE
Issues with Content-Security-Policy When Using Data Manipulation Plugin in Managed Grafana

### ISSUE THREAD

**Issue by alarealeetcodeandplay** [VolkovLabs/volkovlabs-form-panel#413]
**Subject:** Issues with Content-Security-Policy When Using Data Manipulation Plugin in Managed Grafana

Hi,

I am using the MongoDB data source to read data from my MongoDB. I hope to use the “Data Manipulation” plugin in Grafana to send post request to update my documents in the database. However, I encountered an error due to the Content-Security-Policy (CSP):

```
Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at [MongoDB datasource url] because it violates the following directive: “connect-src 'self' …”
```

Grafana's default behavior is to block requests to URLs not specified in the `connect-src` directive, as mentioned in the [official documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-security-hardening/#add-a-content-security-policy).

However, since my Grafana is a managed service and my datasource REST API is hosted on a different domain(e.g. grafana hosted by company A, and datasource hosted by company B), it is not feasible to change the CSP settings on the Grafana side.

My questions are:
1. Given that Grafana and the data source are on different domains, is the current error expected behavior?
2. How can I send a POST request to the MongoDB datasource without changing the CSP?
3. Are there any other way to resolve this issue?

Thank you!

**Comment by vitPinchuk** [comment]
Hi @alarealeetcodeandplay 
You can use  `Data Source` (update action) in Update Request Option instead `POST ` 
and select your MongoDB data source. Specify payload and make update request
Here is perfect [Blog Post: File upload using the Grafana dashboard](https://volkovlabs.io/blog/form-panel-file-upload-20240310/#upload-request) with similar example (for PostgreSQL data source)
