### ISSUE TITLE
Dynamic form via SQL query

### ISSUE THREAD

**Issue by abrahammarco7** [VolkovLabs/volkovlabs-form-panel#416]
Hello, the question is if there is a possibility of inserting the content of the value field of the user's selection of a form element, as a variable within a query. It would be a simple way to make the form more dynamic. I haven't seen anything like this in the documentation, could someone help me?
Below I add an image to make it look clearer, in the image I want to replace the date that I have in the query with the one that the user selects in the "Sample moment" field
Thank you.

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/35036660/83f2a8f6-f4ab-40b0-bd19-709b8bd6a642)

**Comment by mikhail-vl** [comment]
@abrahammarco7 You can use form elements to update Dashboard variables as we explained in the blog post: https://volkovlabs.io/blog/form-panel-use-variables-20240301/.

  Dashboard variables can be used in the Query to help you with dynamic forms.

  We recently published multiple blog post explaining dynamic forms and various solutions: https://volkovlabs.io/blog/tags/data-manipulation/.
