### ISSUE TITLE
Confirmation Window doesn't contain values when they were not changed

### ISSUE THREAD

**Issue by ebabeshko** [VolkovLabs/volkovlabs-form-panel#417]
I need Submit button to be always enabled regardless of value changes, therefore I set Enable Update to Manual

![Update Request](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/63898296/952ff3c3-0d31-4b03-b498-189e35ddeeec)

and specified the following code

`context.panel.enableSubmit()`

in the Custom Code field of Initial Action

Submit button is always enabled now, but if value wasn't changed and I click on Submit, Confirmation Window doesn't contain values at all:

![Confirmation Window](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/63898296/47bf72bb-ce57-4795-90eb-125631d0d43d)

I expected to see old and new values equal here instead of not seeing them at all

When value was changed, everything is fine:

![Confirmation Window](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/63898296/2bcd3af0-21b8-4596-acfc-dc2bc4982d2b)

Is this an intended behaviour?

I am using latest Data Manipulation 3.8.0

**Comment by mikhail-vl** [comment]
@ebabeshko It's expected behavior. We will add an option to display old and new values even when they are not modified in the future release.
