### ISSUE TITLE
How to make submit button always enabled?

### ISSUE THREAD

**Issue by emr17** [VolkovLabs/volkovlabs-form-panel#419]
Currently submit button enables only if i change initial values of form elements. But i want to make that button enabled all the time. How can i do it?
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/79994586/e361dc35-cf0f-4532-bb04-f4a58b26c3cb)

**Comment by ebabeshko** [comment]
I described my steps here:

https://github.com/VolkovLabs/volkovlabs-form-panel/issues/417

**Comment by mikhail-vl** [comment]
@ebabeshko You are correct, `enableSubmit()` is the way.

```
context.panel.enableSubmit()
```

We are working on a documentation PR to update it, should be ready later today/tomorrow: https://github.com/VolkovLabs/volkovlabs.io/pull/686
