### ISSUE TITLE
Disable Submit button with context.panel.disableSubmit() not working

### ISSUE THREAD

**Issue by crl10933** [VolkovLabs/volkovlabs-form-panel#427]
Hi.
I have been trying to make a validation for the form where the submit button is only enabled if a certain criteria is met.
I have tried to force context.panel.disableSubmit() as an always true situation but it's still enabled every time there is a change on the form.

**Comment by vitPinchuk** [comment]
@crl10933 Thank you for the question

A possible solution to help solve your issue

In `Update Request` set `Enable Update` to `Manual`
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/9af96b87-b1b7-4205-9c03-a7bf4413c8b5)

This allows the button to be controlled via code. 

In the section `Element Value Changed` you can add your conditional in the code
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/f492bc01-cbdb-4964-aaad-4ca1500437bf)
