### ISSUE TITLE
Checkbox list with custom options initial values

### ISSUE THREAD

**Issue by imbence** [VolkovLabs/volkovlabs-form-panel#428]
The new form element Type Checkbox list with custom options does not load the initial values from the specified Field Name. If I change the form element type to for example Multi select with custom options it works and adds the selection.

<img width="250" alt="2024-06-27_16-48" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/22945395/381fb771-579c-4438-95b2-11b49299aecd">
<img width="248" alt="2024-06-27_16-46" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/22945395/f1e0eb81-182f-4d10-977c-e902e847ef89">

Is there a different way to get the initial values in?

**Comment by vitPinchuk** [comment]
@imbence Thank you for the question

I tried to reproduce the problem

The data display using Query Field is correct for the two types of elements. 
Please recheck your data or provide more information to reproduce the issue. 

Thank you

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/49be7818-d953-4e30-ba10-0f9228ead8e9)   
  
  

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/0dbbd5d8-6f47-431b-82ea-b52d7d4ab069)

**Comment by imbence** [comment]
Hey, thank you for the answer, 
I meant the Initial values not filling in and not the options to choose from. So if we look at your example under "Initial Request" change "Initial Action" to "Data Source". After setting up the "Initial Request Payload", back in the "Form Element" the "Field Name" option becomes available, and if I fill that in, then it only works with the "Multi select with custom options" Form Element Type and not with Type Checkbox.

**Comment by ashleymcdonald** [comment]
+1 i am also having the same issue, is there any eta to have it fixed? My issue is also with the Postgres datasource
