### ISSUE TITLE
 Business Forms 4.0.0: TypeError: Cannot read properties of undefined (reading 'panel')

### ISSUE THREAD

**Issue by ebabeshko** [VolkovLabs/volkovlabs-form-panel#431]
After upgrading from 3.8.0 to 4.0.0 operation of my panel was broken, the following error was shown after using Submit button:

![Error](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/63898296/d4703d9e-6df0-46bb-bb52-c6ca479f965c)

Found out that this behavior was caused by replacement of `context.panel` in Custom code by `context.panel.context.panel` automatically after upgrade:

![context.panel](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/63898296/ae2afdef-bb42-4906-b3f6-49ac39de3876)

After changing `context.panel.context.panel` back to `context.panel` panel is working again

**Comment by mikhail-vl** [comment]
@ebabeshko It's limitation of the migration we implementation in v4. All parameters were moved to `context` and if you are already using `context`, please remove it.
