### ISSUE TITLE
Data Manipulation Panel Error write value zero

### ISSUE THREAD

**Issue by JM-Stange** [VolkovLabs/volkovlabs-form-panel#434]
Hi,
I'm using the Data Manipulation Panel Version 3.8.0 with MS SQL Server.
If I try to update an integer database field (NextWaitTime) with zero value I get an error message.
The value is undefined instead of zero: **NextWaitTime=undefined**
All other values are write to the database.
Normally this should be fixed  (https://github.com/VolkovLabs/volkovlabs-form-panel/pull/288)
What could be the problem?

Error Message:
Request
{"status":400,"statusText":"Bad Request","data":{"results":{"A":{"error":"db query error: mssql: Ungültiger Spaltenname 'undefined'.","status":500,"frames":[{"schema":{"refId":"A","meta":{"typeVersion":[0,0],"executedQueryString":"Update ECSExport.dbo.UnitStates SET Status=1,MessageBox=' ', NextWaitTime=undefined WHERE UnitName = 'Anlage 02'"},"fields":[]},"data":{"values":[]}}]}}},"config":{"method":"POST","url":"api/ds/query","data":{"queries":[{"datasourceId":1,"refId":"A","rawSql":"Update ECSExport.dbo.UnitStates SET Status=1,MessageBox=' ', NextWaitTime=undefined WHERE UnitName = 'Anlage 02'","format":"table"}]},"retry":0,"headers":{"X-Grafana-Org-Id":1},"hideFromInspector":false}}

**Comment by vitPinchuk** [comment]
@JM-Stange Thank you for your question

I repeated the steps with the field update. I used version 3.8.0 and also the PostgreSQL data source.
In networks when making the update request I see that my payload has the correct values, including `0` value from the Number Input field
![Снимок экрана от 2024-07-08 09-56-50](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/1b83dfc0-0aed-4144-b62b-07e30f25fc89)

I also use version [4.0.0](https://github.com/VolkovLabs/volkovlabs-form-panel/releases/tag/v4.0.0)
I see the correct behavior for setting values in the payload from the elements

Please, update Data Manipulation to current version and try to repeat issue. It should be working correct on current version

Thank you 
 
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/366e3f63-e7c9-4a42-95e5-b3f2345d9c33)

**Comment by JM-Stange** [comment]
Vitali, 
I have installed version 4. The same error occurs with zero values.
Writing to the DB works fine with values greater than 0.

![grafik](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/174711609/da5b4959-b3be-4540-98ae-65b5f52bef21)


I am using Microsoft SQL Server with the following table:
```

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UnitStates](
	[UnitName] [nvarchar](20) NOT NULL,
	[UnitState] [int] NULL,
	[MessageBox] [nvarchar](200) NULL,
	[Status] [int] NULL,
	[DefaultWaitTime] [int] NOT NULL,
	[NextWaitTime] [int] NOT NULL,
	[PlannedStart] [datetime] NULL,
 CONSTRAINT [PK_UnitStates] PRIMARY KEY CLUSTERED 
(
	[UnitName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UnitStates] ADD  CONSTRAINT [DF_UnitStates_NextWaitTime]  DEFAULT ((0)) FOR [NextWaitTime]
GO
```

Here is the update statement from the panel
```
/**
 * Data Source payload
 */
return {
  rawSql: `Update ECSExport.dbo.UnitStates SET Status=${payload.StatusNew},MessageBox='${payload.MessageNew}', NextWaitTime=${payload.WaitTimeNew} WHERE UnitName = '$FilterUnitName'`,
  format: 'table',
```
};

**Comment by vitPinchuk** [comment]
@JM-Stange Thanks for providing more details 

Please in code editor at line 4, comment or remove the following code

```js
  if (!element.value) {
    return;
  }

```

**Comment by JM-Stange** [comment]
Vitali,
now it works.
Thank you!
Regards
Andreas
