### ISSUE TITLE
[Question] Infinity Datasource with Update Request

### ISSUE THREAD

**Issue by mschweig** [VolkovLabs/volkovlabs-form-panel#440]
Hello, 

how can I use the Infinity Datasource to do a Update Request with the specified field from the Form Elements? 

For example: Form Element Custom Select is "command1" 

When clicking on "Submit" a GET/POST request should be carried out via Infinity Datasource to the desired API like that:

https://demo-api?param=command1

Is that possible? 

Thanks
Best regards.

**Comment by vitPinchuk** [comment]
@mschweig Thank you for your question.

Use Infinity Datasource. For example, I use endpoint: `https://jsonplaceholder.typicode.com/posts`  
  

<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/370486c6-d881-4758-bdea-13ca6ead3250)</kbd>


Add 3 element for Title, Body, and for user Id  
  

<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/e9f13004-d698-4ecf-8419-38669c16f5bd)</kbd>

Here is my Initial request settings
<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/f8e343af-b830-4c70-b04e-f6194626f1ff)</kbd>

<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/b3d6c381-fe5f-42a5-a2e9-13eca58b6632)</kbd>

And an example of creating an update request with the specified field from form elements:  
 
`Update Action` -> `Data Source`
`Data Source` -> `Infinity`

custom code example 
```js
if (context.panel.response) {
  context.grafana.notifySuccess(['Update', 'Values updated successfully.']);
  context.panel.initialRequest();
} else {
  context.grafana.notifyError(['Update', 'An error occurred updating values.']);
}
```

<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/25c860be-c630-405f-a21b-801368e92136)</kbd>
  
Please create a payload using the panel elements. 
The code editor should return the appropriate payload.
Create payload:

```js
let payload = {
  title: '',
  body: '',
  userId: ''
}
context.panel.elements.forEach((element) => {
  console.log('console >> element', element)
  if (element.id === "postTitle") {
    payload.title = element.value
  }

  if (element.id === "postBody") {
    payload.body = element.value
  }

  if (element.id === "userId") {
    payload.userId = element.value
  }

})

return payload

```
<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/d93d53e5-5ad6-4097-8574-29ab6d513484)</kbd>
  
  

Next, we should use payload in request via Infinity Data Source. Use for that `Query Editor` field in Update Request
Method: `POST`  
URL: `https://jsonplaceholder.typicode.com/posts`
And `Headers, Body, Request params` have `URL options`  
Body Type: `Raw`
Body Content Type: `JSON`
Body Content (for example): 
```js
{
  "title": "${payload.title}",
  "body": "${payload.body}",
  "userId": "${payload.userId}"
}
``` 
Here we use the payload we got from the `Create Payload` code editor.
<kbd>
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/fea104f4-ccbb-4774-aa1c-f27516ef095c)
</kbd>
  
  

And after click "Submit" button I see in Network my payload in body:  
  
<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/ff03e6da-1851-4a04-926d-1ad1a629db16)</kbd>

In the same way we can add parameters from the payload to URL
As example:  
`https://jsonplaceholder.typicode.com/posts?param=${payload.title}`    

<kbd>![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/146737590/4acfbb13-c886-4e4e-9f40-a6a138e27fdc)</kbd>

**Comment by mikhail-vl** [comment]
@vitPinchuk Well done! Could you please create a blog post how to use Business forms with Infinity Data Source based on this content.

**Comment by mschweig** [comment]
Hi @vitPinchuk thanks, that's amazing! I had to update to 4.1.0, it was not working with prior versions. 

I also combined Infinity with the base64 Plugin to show Images from HTTP APIs, what a great add-on :)
