### ISSUE TITLE
Grafana 11 Support required

### ISSUE THREAD

**Issue by fredpan** [VolkovLabs/volkovlabs-form-panel#442]
Hi, 

Since Grafana 11 now is generally available, do you have plan to upgrade this plugin to make it works with Grafana 11?

Thanks

**Comment by fredpan** [comment]
Seems like I used the wrong version, current version works perfectly with Grafana 11

**Comment by mikhail-vl** [comment]
@fredpan We just released version 4.1.0, which are pending on Grafana review and should be available in Grafana Catalog soon.

**Comment by fredpan** [comment]
> @fredpan We just released version 4.1.0, which are pending on Grafana review and should be available in Grafana Catalog soon.

Can't wait to upgrade it :)

**Comment by mikhail-vl** [comment]
@fredpan While waiting you can enjoy our latest plugin overview: https://www.youtube.com/watch?v=ulbe8U8-IFA
