### ISSUE TITLE
File Form Element - Submit button remains enabled after uploaded file is deleted

### ISSUE THREAD

**Issue by canob** [VolkovLabs/volkovlabs-form-panel#444]
Hi,

I was reviewing the File Form Element in Data Manipulation Panel version 3.8.0, and I found what maybe is a bug:

Before you upload a file, the Submit button is disabled, which is correct:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/30271927/b18578ca-ea33-44a1-9959-144cbc79603b)
After you upload the file, the Submit button is enabled, which is correct:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/30271927/2d41eef5-b637-4325-bb39-f5742a5d6613)
But if you remove the uploaded file, the Submit button remains enabled, which I think it is not correct:
![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/30271927/4d6fce11-f321-4ff3-af20-becfb2144c5a)

I can confirm that this behavior is identical on Business Form Panel 4.1.0.

Can anyone tell me if this is the expected behavior, and if there is a way to avoid this?

Thanks in advance.

**Comment by mikhail-vl** [comment]
@canob Thank you for reporting this issue. We will look into it.
