### ISSUE TITLE
Struggling with business from version 4.x

### ISSUE THREAD

**Issue by marciop975** [VolkovLabs/volkovlabs-form-panel#456]
I have some dashboard that upload data in mySQL database by reading one CSV.  
I have also an dashboard to upload a image into mySQL database by reading a jpg files using business forms  
Since version 4.X those dashboards stopped working. 
 
To upload the image fine content I have in the payload the code :
******************
const payload = {};

context.panel.elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
});

const readImage = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const base64Content = reader.result.split(',')[1]; // Remove the data URL prefix
      resolve({
        fileName: file.name,
        base64Content: base64Content,
      });
    };
    reader.onerror = reject;
  });

/**
 * Data Source payload
 */
const getPayload = async () => {
  const file = payload.file[0];
  const imageData = await readImage(file);
  return payload;
};

return getPayload();
*****************

IN QUERY Editor I have :
***************
UPDATE informativos.rh_test 
SET file = ${payload.fileName}  , content = ${payload.base64Content}
WHERE id='$id';
***************

IN CUSTOM CODE in update request I have :
**************
if (context.panel.response && context.panel.response.ok) {
  context.grafana.notifySuccess(['Update', 'Values updated successfully.']);
  context.panel.initialRequest();
} else {
  context.grafana.notifyError(['Update', 'An error occurred updating values.']);
}
**************
ON PREVIUS VERSIONversion of business forms until 3.8 this below code worked fine:
*****************************
const payload = {};

elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
});

const readImage = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const base64Content = reader.result.split(',')[1]; // Remove the data URL prefix
      resolve({
        fileName: file.name,
        base64Content: base64Content,
      });
    };
    reader.onerror = reject;
  });

/**
 * Data Source payload
 */
const getPayload = async () => {
  const file = payload.file[0];
  const imageData = await readImage(file);

  return {
    rawSql: `UPDATE informativos.rh SET file ='${imageData.fileName}' , content = '${imageData.base64Content}'
            WHERE id='$id';`,
    format: "table",
  };
};

return getPayload();
******************************

I need support to understant how to fix to use business forms 4.1.
I did the dashboard by the instruction on https://volkovlabs.io/blog/form-panel-file-upload-20240310/ 
Could you please update that with business forms 4.1 changes ?

**Comment by vitPinchuk** [comment]
@marciop975 Thank you for your question

According instruction on [upload](https://volkovlabs.io/blog/form-panel-file-upload-20240310/)

code in blog for 3.8.0

```js
const payload = {};

elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
});

const toBase64 = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
  });

/**
 * Data Source payload
 */
const getPayload = async () => {
  const file = payload.file[0];
  const base64 = await toBase64(file);

  return {
    rawSql: `INSERT INTO files (name, file)
VALUES ('${file.name}', '${base64}');`,
    format: "table",
  };
};

return getPayload();
```  
  

from 4.x version
code to copy `Create Payload`:  

```js 
const payload = {};

context.panel.elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
})

const toBase64 = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
  });


/**
 * Data Source payload
 */
const getPayload = async () => {
  const file = payload.file[0];
  const base64 = await toBase64(file);

  return {
    file,
    base64,
  }
}

return getPayload();
```

and `Query Editor`:

```js
INSERT INTO files (name, file)
VALUES ('${payload.file.name}', '${payload.base64}');
```
  

Here is a similar part of the documentation with an example of version 4.x and a comparison with the previous version: [frontend data source](https://volkovlabs.io/plugins/volkovlabs-form-panel/data-flow/#query-editor-and-frontend-data-source)
  
  
In your question and example:
```js
const getPayload = async () => {
  const file = payload.file[0];
  const imageData = await readImage(file);
  return payload;
};
return getPayload();
```

You are returning `payload` with containing `file` object. And then in `QUERY Editor` you try to get  `payload.fileName` and `payload.base64Content` which is not in payload.

Please, you can use `console.log()` to check your payload  
 
```js

const getPayload = async () => {
  const file = payload.file[0];
  const imageData = await readImage(file);
  console.log('check payload', payload)
  return payload;
};
return getPayload();

```

Please, you can use the following code example to return appropriate payload data:   

```js
/**
 * Data Source payload
 */
const getPayload = async () => {
  
  const file = payload.file[0];
  const imageData = await readImage(file);
  /**
   * Check image data imageData
   */
  console.log('console >>> imageData', imageData)
  return {
    fileName: imageData.fileName,
    base64Content: imageData.base64Content,
  }

}
```

Full code for   `Create Payload`

```js
const payload = {};

context.panel.elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  payload[element.id] = element.value;
})

const readImage = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const base64Content = reader.result.split(",")[1]; // Remove the data URL prefix
      resolve({
        fileName: file.name,
        base64Content: base64Content,
      });
    };
    reader.onerror = reject;
  });

/**
 * Data Source payload
 */
const getPayload = async () => {

  const file = payload.file[0];
  const imageData = await readImage(file);
  /**
   * Check image data imageData
   */
  console.log('console >>> imageData', imageData)
  return {
    fileName: imageData.fileName,
    base64Content: imageData.base64Content,
  }

}

return getPayload();
```

**Comment by mikhail-vl** [comment]
@vitPinchuk Please update in the blog: https://volkovlabs.io/blog/form-panel-file-upload-20240310/

**Comment by mikhail-vl** [comment]
Blog post updated: https://volkovlabs.io/blog/form-panel-file-upload-20240310/

**Comment by mikhail-vl** [comment]
@marciop975 Great to hear!

  Let us know if there is anything else!
