### ISSUE TITLE
context.panel.onOptionsChange constantly reloading

### ISSUE THREAD

**Issue by trhphuc** [VolkovLabs/volkovlabs-form-panel#458]
I am having problems using context.panel.onOptionsChange in Initial Request to dynamically update the sections' name and id in the layout component of context.panel.options.

The Initial Request code seems to be constantly running despite no further requests to the data source. This significantly slows down the interface and affects the users' experiences.

Here's how one can recreate the problem:

```
context.panel.onOptionsChange({
    ...context.panel.options,
    layout: {
        ...context.panel.options.layout,
        sections: [{
            id: 'test',
            name: 'Test'
        }]
    }
});
```

I am using Business Form v4.2 on Grafana v10.2.0. Thank you!

**Comment by mikhail-vl** [comment]
@trhphuc Thank you for reporting the issue.

  We will investigate and get back to you.

**Comment by vitPinchuk** [comment]
@trhphuc Thank you for the question.

`context.panel.onOptionsChange` refresh the panel. 

Please, check **Synchronize with data** option in Initial Options. If **Synchronize with data** enable, `context.panel.onOptionsChange` refresh panel and call Initial request constantly.

To avoid this behavior, please,  disable **Synchronize with data** option. 

Remove or comment or part of code with `context.panel.onOptionsChange` 

```js
  // context.panel.onOptionsChange({
  //   ...context.panel.options,
  //   layout: {
  //     ...context.panel.options.layout,
  //     sections: [{
  //       id: 'test',
  //       name: 'Test'
  //     }]
  //   }
  // });
```

Then, please disable **Synchronize with data**. After applying the option, you can use `context.panel.onOptionsChange` in the Initial code.

![image](https://github.com/user-attachments/assets/ef391eb7-e5dd-4215-81d4-6d2b416f4c89)
