### ISSUE TITLE
[Question] Automatic set to blank values after post request

### ISSUE THREAD

**Issue by henjoe** [VolkovLabs/volkovlabs-form-panel#56]
Hi,

I wonder if there is a way to automatically set to "blank" values of all form once the user clicked the "Submit button"? 
![image](https://user-images.githubusercontent.com/49782655/178130918-1fec195b-d859-4d0b-88e2-4a309ce646b3.png)

I found that there is a custom code where you can run after the post request, however I don't know how to access those "form elements" to set their values to be equal to nothing once post request is done, what I only tried is to have an "alert" function which works well.

![image](https://user-images.githubusercontent.com/49782655/178130956-8588e0ff-f3cc-432c-b0a2-18dd65b69a57.png)

Thank you.

Regards,
Henjoe

**Comment by mikhail-vl** [comment]
@henjoe Thank you for trying the plugin.

Values for the form can be clearout using a custom Code

```
elements.map((element) => {element.value = ''});
```

It's partially explained in the article, but we should make it more clear: https://volkovlabs.com/data-manipulation-panel-plugin-for-grafana-97f9af2c67e0

Please let me know if there is anything else.

**Comment by henjoe** [comment]
Hi @mikhail-vl 
Thanks for the response! 
Will try this and get back this once done. 

Regards,
Henjoe

**Comment by henjoe** [comment]
Hi @mikhail-vl ,

This code:
elements.map((element) => {element.value = ''})

works well when putting all the value to "null" or blank. 

However, what if a specific element only that I would like to set it to blank? 
Is there a way to specify their IDs? 
For example, I only want the Name (with id name) the only element to set in blank?

Thanks!

Regards,
Henjoe

**Comment by mikhail-vl** [comment]
Hello @henjoe 

  It's an advantage of the custom code. You can make it as flexible as possible:

  For `name` only it will look like that:
```
elements.map((element) => {
   if (element.id === 'name') {
     element.value = '';
   };
})
```

  Please let me know if you need anything else.

**Comment by henjoe** [comment]
Thanks @mikhail-vl !

All works!

Regards,
Henjoe

**Comment by mikhail-vl** [comment]
@henjoe,

  Great for confirming!

  Do you mind sharing a couple of finished screenshots with a description of the project? I would love to share with the community. If you can't, that's totally fine.

**Comment by henjoe** [comment]
Sure @mikhail-vl ! 

This is totally fine, I'll get back to this thread once done :)

**Comment by henjoe** [comment]
Hi @mikhail-vl ,

So here is what I done so far in Data Manipulation Panel.
I used the panel to get the basic information we needed, when the "submit" button is clicked, it goes to my backend API (nodered) and it send the data fo my InfluxDB. Then of course, from influxDB, you can visualize things in Grafana. 

![image](https://user-images.githubusercontent.com/49782655/179382298-f85d6aa2-dd91-4080-85f8-6d80b50a7842.png)

I blurred out the table for data privacy. 

Thanks for this wonderful panel! 

Regards,
Henjoe
