### ISSUE TITLE
Facing Issue in POST 

### ISSUE THREAD

**Issue by RohitSharma2k122** [VolkovLabs/volkovlabs-form-panel#62]
![Data Manipulation](https://user-images.githubusercontent.com/110539162/182600491-10ee424c-225f-4d58-aa1a-23e08aa68ce6.PNG)

Not able to post the request using direct api created in .netcore 
http://localhost:61761/api/Test/{ID}/{Name}/{Email}

**Comment by mikhail-vl** [comment]
@RohitSharma2k122 Thank you for your interested in the Data Manipulation plugin.

  Plugin is doing POST requests with parameters in the body. Does .netcore support POST with body? I am not familiar with it.
  We have an Node.js example for reference: https://github.com/VolkovLabs/volkovlabs-form-panel/blob/main/server-pg/server.ts

  Please let me know.

**Comment by RohitSharma2k122** [comment]
HI @mikhail-vl 

This is my Json data, Now i am passing on POST requests with parameters in the body.  Can you help me where its missing plz suggest.

{
  "id": 4,
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "type": "volkovlabs-form-panel",
  "title": "Feedback",
  "datasource": {
    "uid": "grafana",
    "type": "grafana"
  },
  "options": {
    "initial": {
      "method": "-",
      "contentType": "application/json",
      "code": "console.log(options, data, response, elements, locationService, templateService)",
      "highlight": false,
      "highlightColor": "red"
    },
    "update": {
      "method": "POST",
      "contentType": "application/json",
      "code": "console.log(options, data, response, elements, locationService, templateService)",
      "confirm": false,
      "header": [],
      "url": "http://localhost:61761/api/Test"
    },
    "layout": {
      "variant": "single"
    },
    "buttonGroup": {
      "orientation": "center",
      "size": "md"
    },
    "submit": {
      "variant": "primary",
      "foregroundColor": "text",
      "backgroundColor": "semi-dark-green",
      "icon": "anchor",
      "text": "Submit"
    },
    "reset": {
      "variant": "destructive",
      "foregroundColor": "yellow",
      "backgroundColor": "purple",
      "icon": "process",
      "text": "Reset"
    },
    "elements": [
      {
        "id": "ID",
        "labelWidth": 10,
        "section": "",
        "title": "ID",
        "tooltip": "",
        "type": "string",
        "value": "1"
      },
      {
        "id": "Name",
        "labelWidth": 10,
        "section": "",
        "title": "Name",
        "tooltip": "",
        "type": "string",
        "value": "Rohit"
      },
      {
        "id": "Email",
        "labelWidth": 10,
        "section": "",
        "title": "Email",
        "tooltip": "",
        "type": "string",
        "value": "Rohit.@gmail.com"
      }
    ]
  },
  "targets": [
    {
      "refId": "A",
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      }
    }
  ]
}

**Comment by mikhail-vl** [comment]
@RohitSharma2k122 I see that your URL is `"url": "http://localhost:61761/api/Test"`.

  Are you running Grafana and `.netcore` on your localhost? This is the URL your browsers will make a POST call, so you should be able to reach it.

  What do you see in the Browser's Console -> Network?

**Comment by RohitSharma2k122** [comment]
**Thanks @mikhail-vl for helps. Appreciate your support.**

**Am able to Post the data back to data source.**

One last question, Not able to clear the value of the form on click of reset button..

**Comment by mikhail-vl** [comment]
@RohitSharma2k122 The Reset button perform Initial Request and runs custom code.
 If you don't use Initial Request you can clear out all the fields using custom code:

```
elements.map((element) => {element.value = ''});
```

Or any particular fields if required

```
elements.map((element) => {
   if (element.id === 'name') {
     element.value = '';
   };
})
```

Please let me know if there is anything else.

**Comment by RohitSharma2k122** [comment]
Thanks so much @mikhail-vl.

Its works for me.

**Comment by mikhail-vl** [comment]
@RohitSharma2k122 Thank you, let us know if there is anything else.

**Comment by RohitSharma2k122** [comment]
Thanks @mikhail-vl !

All works!
