### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by Castlesai** [VolkovLabs/volkovlabs-form-panel#69]
Hello Team I am not able to reset panal data using reset button and when i am using date and time as parameter in input panel  error is occuring

**Comment by mikhail-vl** [comment]
@Castlesai `Reset` button executes Initial Request and custom code. It does not reset data by itself. If you want to clear all fields or a particular field, there is a sample code in README: https://github.com/VolkovLabs/volkovlabs-form-panel#clear-elements-values-after-submit-or-on-reset-button-click

Please provide more details on how you set date and time and what kind of error you see.

**Comment by mikhail-vl** [comment]
@Castlesai Please let us know if you need anything else.

**Comment by Castlesai** [comment]
Hello team when I select date and time in panel and try to submit at that time some error is showing 
![Uploading IMG_20220815_003825.jpg…]()

**Comment by mikhail-vl** [comment]
@Castlesai Could you please post the image again?

**Comment by Castlesai** [comment]
![Uploading IMG_20220815_003825.jpg…]()

**Comment by mikhail-vl** [comment]
@Castlesai Unfortunately, there is something wrong with how you upload the image or GitHub.

Can you download your uploaded image?

**Comment by mikhail-vl** [comment]
@Castlesai It's not clear what the issue is until I see the image.

Please upload it again and reopen the issue if required.

**Comment by Castlesai** [comment]
Hello VolkovLabs/volkovlabs-form-panel
   I tried with refresh I tried code which you shared with me.
   elements.map((element) => {
if (element.id === 'date') {
element.value = '';

}
});
 Can you please go through this images. I have attached with this email.

**Comment by Castlesai** [comment]
can we connect through google meet if it is possible?
