### ISSUE TITLE
Add variables in URL to call from form elements.

### ISSUE THREAD

**Issue by ytiruces** [VolkovLabs/volkovlabs-form-panel#78]
Hi!

I need to insert a variable from form elements into the query link. How can i do this?

I want do create payload from form elements and then create API call.

Dashboard variables not suitable.

**Comment by ytiruces** [comment]
@mikhail-vl, is it possible?

**Comment by mikhail-vl** [comment]
Hello @ytiruces,

  Thank you for the great question! In this case I would just use the Custom Code to do the request and skip Update Request.

![Screen Shot 2022-08-26 at 09 11 51](https://user-images.githubusercontent.com/47795110/186911352-d91d7495-7a43-449f-be58-4c8c55685b29.png)
 
  Here is the code example. You can get the specific `element` value using `body[element.id]` in the `url`:

```
/**
 * Set body
 */
const body = {};
options.elements.forEach((element) => {
  body[element.id] = element.value;
});

/**
 * Set URL
 */
const url = `http://localhost:3001/${body['name']}`;

/**
 * Fetch
 */
const resp = fetch(url, {
  method: 'POST',
  body: JSON.stringify(body),
}).catch((error) => {
  console.error(error);
}).then((resp) => {console.log(resp)});
```

  Let me know if it works for you.
  We will include it in our next video with other tips and tricks for the panel.

**Comment by ytiruces** [comment]
Added headers and worked as it should!

```TypeScript
headers: {
    'Content-Type': 'application/json',
    'PRIVATE-TOKEN': '$token'
  },
```

TY @mikhail-vl

**Comment by mikhail-vl** [comment]
@ytiruces Thank you for confirming. We updated the README with the code example.

  Please let me know if there is anything else.
  If you have an interesting use case for the panel, don't hesitate to share.
