### ISSUE TITLE
how exactly to get the response data from the initial request http GET for form element?

### ISSUE THREAD

**Issue by lynhnn** [VolkovLabs/volkovlabs-form-panel#86]
My http GET return JSON data on the "network/preview" debug tab but I'm not able to get to that JSON in the custom code to populate the data to the drop down list. "console.log(response)" doesn't show this JSON or anything related to the response I see elsewhere. Please help!

**Comment by mikhail-vl** [comment]
Hello @lynhnn, that's is strange:

  Do you use the latest version, 2.4.0, we published recently? I just verified it and everything looks good for me.

  Do your panel's options look similar?
![Screen Shot 2022-09-02 at 14 24 45](https://user-images.githubusercontent.com/47795110/188215230-6aef0453-b30a-44ae-b66a-7cec8b9d2667.png)

**Comment by lynhnn** [comment]
Yes I have version 2.4.0 and the panel edit look similar to what you have. The "console.log(response)" would give me the Object on the console tab like "Response { type: 'cors', url: 'https://....', redirected: false, status: 200, ok: true ...}" I don't know how to get the actual data from this to assign to my dropdown list values. Again, I can see the response JSON data  from the browser tab "Network/Preview"

**Comment by lynhnn** [comment]
It would be nice if you have an example of how to extract the data from the HTTP GET and use that in the variable input values like for the dropdown list items. I tried to look everywhere on your website and internet but not able to find a sample or instruction of how to do that. I think an example is extremely useful.

**Comment by mikhail-vl** [comment]
There are examples of the server implementations and dashboards in the repository.

They should be also explained in our videos.

**Comment by lynhnn** [comment]
I watched your video and they don't mention how to extract the values from an initial request GET http. I spent over 4 hours trying to get this working. I hope you can give me a direct link or an example of how to get the values out. The logic and how it works is totally great. However, this little detail of how to handle the data after the request and get them into the value for the form input is still a mystery. BTW, the "Custom Code" text block to execute after initial request always remove/clear my code after I click the refresh to fetch the data. Please help me with a bit more details. Thanks

**Comment by mikhail-vl** [comment]
@lynhnn Thank you for the feedback. We understand what is missing and will update the README tomorrow.

Let me try to explain how the Initial Request works. If GET initial request is selected, then it will be executed when the form is loaded, or the Reset button is pressed.

In our example, the Node.js server (https://github.com/VolkovLabs/volkovlabs-form-panel/blob/main/server/server.ts) returns JSON in the format:

```
{
    "name": "Name",
    "amount": 30,
    "updated": false,
    "step": 4
}
```

Form Panel automatically parses this JSON and sets values for elements with ids: `name`, `amount`, `updated` and `step` defined in the Panel options. You can find the dashboard with example panels in the `dashboards` folder: https://github.com/VolkovLabs/volkovlabs-form-panel/blob/main/provisioning/dashboards/panels.json

So, you don't need to parse values manually, unless you need to update them from initial values or clear some fields, which is explained in the README file.

Please let me know if it's clear. You are welcome to send the JSON response and panel options to give more details.

**Comment by lynhnn** [comment]
Ok, for my case, the http GET request would return a generic JSON and I would use a known path to get to the array of values (for dropdown list). I was hoping that your GET hook would allow me to continue to extract the data using the custom code block and set the data using the global variable name for that input form. I'm still think your plugin should support this generic REST endpoint. It is a must because these endpoints exist across multiple applications even before the UI usage and reuse it in your plugin is an obvious choice.  Here is a sample of response from my GET request and I would like to get the array of values from this.aggregations.os.buckets
<img width="832" alt="Screen Shot 2022-09-02 at 4 37 01 PM" src="https://user-images.githubusercontent.com/6796611/188246603-d2f9534c-f7d9-4b3d-b088-20baea40e2f6.png">

**Comment by mikhail-vl** [comment]
@lynhnn Finally, I got it; sorry, it was a long Friday. Thank you for providing the example.

Unfortunately, you can't get the Response's body in the custom code for the Initial Request because it was already read and parsed inside the plugin. I can add parsed `json` parameter to the Custom Code function in the upcoming release.

But you don't need to wait for the release. You can select Initial Request as `-` and create your own request inside Custom Code:

```
const bucketsSelect = elements.find((element) => element.id === 'buckets');

/**
 * Set URL
 */
const url = `http://localhost:3001/test`;

/**
 * Fetch
 */
const resp = fetch(url, {
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'PRIVATE-TOKEN': '$token',
  }
})
  .catch((error) => {
    console.error(error);
  })
  .then(async (resp) => {
    const body = await resp.json();
    console.log(body);

    bucketsSelect.options = body.aggregations.os.buckets.map((value) => {
      return { label: value, value };
    });
  });

onOptionsChange(options);
```

Please let me know if it works for you. Let me know if not, I will add `json` parameter over the weekend and create a minor release, which you can download from GitHub.

**Comment by lynhnn** [comment]
Thanks @mikhail-vl for showing this code. I think this code will work. The next question is can I run multiple of these as I have many inputs to be fetched from various REST endpoints?
Please let me know when I can get the 'json' update code and try. Thanks again!!

**Comment by mikhail-vl** [comment]
@lynhnn, I am sorry for the delay, I will have time to add `json` tomorrow.
  Initial request by design is only one, I don't want to complicate the logic of the plugin.

  To fetch multiple endpoint, you can have one Initial Request and other can be fetched inside Custom Code.
  I would recommend to use multiple JSON Data Source instead and read data from the data sources as we showed in the examples.

**Comment by mikhail-vl** [comment]
@lynhnn Data Manipulation panel 2.5.0 released: https://github.com/VolkovLabs/volkovlabs-form-panel/releases/tag/v2.5.0.

  Please try and let me know if there is anything else.
