### ISSUE TITLE
reload only the panel, not the entire page after update

### ISSUE THREAD

**Issue by absvm** [VolkovLabs/volkovlabs-form-panel#87]
Hi,

One of the examples contains custom code to reload the page after an update. It uses location.reload():

`if (response && response.ok) {
  location.reload();
} else {
  alert(`Error: ${response.status}`);
}`

However, that reloads the whole page. It would be much faster and more elegant if I can reload only the panel for which I submit the update, exactly like what the reset button does. Is this possible? Maybe by triggering the reset button itself?

**Comment by mikhail-vl** [comment]
@absvm I am sorry for the delay, I like the idea of being able to trigger the Initial Request (Reset) button when clicking on the Update Request.

  I am going to expose `initialRequest()` function, which can be called in the Custom Code.
  Will it work for you?

**Comment by mikhail-vl** [comment]
@absvm Feature implemented and will be available in the upcoming release (end of this or start next week).

  Please let us know if there is anything else.

**Comment by absvm** [comment]
Thank you @mikhail-vl, great. Looking forward to try it.

**Comment by mikhail-vl** [comment]
@absvm Data Manipulation panel 2.5.0 released: https://github.com/VolkovLabs/volkovlabs-form-panel/releases/tag/v2.5.0.

  Please try and let me know if there is anything else.

**Comment by mikhail-vl** [comment]
@absvm Thank you for confirming.

  We appreciate your support.
  Please let us know if there is anything else.
