### ISSUE TITLE
Is it possible to interact from with other panels from data manipulation one?

### ISSUE THREAD

**Issue by agriii927** [VolkovLabs/volkovlabs-form-panel#93]
Is it possible to interact from with other panels from data manipulation one?
My case is: I send my post query to REST API, get the answer which is shown in the next data manipulation row with prediction label. 
But it doesn't look fully distinguishable and that's why i want to highlight my result using stat panel because there I can set the size of query result text etc.

![изображение](https://user-images.githubusercontent.com/67045661/192958992-47287663-dd1f-466d-8c58-8639e0fc8d92.png)

Maybe it's possible by using templateService because it provides access to variables and i can connect my result from data manipulation panel with dashboard variable?

**Comment by mikhail-vl** [comment]
@agriii927 That's a great question and it was recently asked on our YouTube channel.

`templateService` is available in the Custom Code and it allows to get values for variables.
`locationService` is available as well and allows to set variable: https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/#set-a-variable-from-your-plugin

Here is the example of the Update Request:
```
if (response && response.ok) {
  response.json().then(resp => {
    console.log(resp);
    locationService.partial({ 'var-var': resp['name'] }, true);
  });
}
```

You should be able to use Variable in other panels. Please let me know if it works for you.

**Comment by mikhail-vl** [comment]
@agriii927 To update `vartest` variable it should be `var-vartest` in the code:

```
if (response && response.ok) {
  response.json().then(resp => {
    console.log(resp);
    locationService.partial({ 'var-var': resp['name'] }, true);
  });
}
```

  You should be able to see it updated to the `name` value in JSON.
  Please let me know if it works.

**Comment by agriii927** [comment]
Hello! It works! My problem was using "vartest" except "var-vartest".
