### ISSUE TITLE
Form Elements Validation 

### ISSUE THREAD

**Issue by Castlesai** [VolkovLabs/volkovlabs-form-panel#94]
Hello @mikhail-vl,
I have tried elements validation in the Data Manipulation panel it is not showing any popup or warning if a user is entered data above the limits can you help my validation?
below is my panel configuration.
![Screenshot from 2022-09-29 14-38-56](https://user-images.githubusercontent.com/40688966/192998617-e7fd844e-a68c-4393-9009-73f4fbe99984.png)
![Screenshot from 2022-09-29 15-14-46](https://user-images.githubusercontent.com/40688966/192999136-8e8d9d84-a2d9-43e7-b5bf-446cded9357d.png)

**Comment by mikhail-vl** [comment]
@Castlesai Thank you for opening the issue. `Min` and `Max` parameters define the range for Input element, but they don't enforce manual input.

  Updated in #95 and will be a part of the upcoming release.

**Comment by mikhail-vl** [comment]
@Castlesai PR Merged and will be a part of the release later today.

  Please let us know if you need anything else.
