### ISSUE TITLE
Status notification after submit form

### ISSUE THREAD

**Issue by ytiruces** [VolkovLabs/volkovlabs-form-panel#98]
Hi!

How can I create status notification after submit form? \
Like this:

![image](https://user-images.githubusercontent.com/8374107/194008831-5cdacdb8-4c76-481c-9664-636c0a02e875.png)

With message "Form submitted successfully" + maybe some link or remote data from request response.

TY!

**Comment by mikhail-vl** [comment]
@ytiruces It's a great question. You should be able to do it in Custom Code after Update Request like `alert`.

  I will take a look into Grafana's notification and get back to you.

**Comment by ytiruces** [comment]
window.alert() not in grafana style.

**Comment by mikhail-vl** [comment]
@ytiruces I looked at how notifications are done in Grafana and looks like they are not exposed to plugins.

  I will look more closely over the weekend.
