### ISSUE TITLE
Initial GET request date time formatting

### ISSUE THREAD

**Issue by Castlesai** [VolkovLabs/volkovlabs-form-panel#99]
Hello @mikhail-vl,
I am using an initial GET request to populate the data, all the string fields get populated correctly but date-time field is not properly populated kindly see the below images of actual and expected results. Also unable to open the calendar option to select date-time after the initial GET request is finished.
Actual 
![Screenshot from 2022-10-07 14-12-56](https://user-images.githubusercontent.com/40688966/194512343-15cd7c37-1cf8-43ef-a771-751e2dd067de.png)

Error while selecting the calendar option
![Screenshot from 2022-10-07 14-13-16](https://user-images.githubusercontent.com/40688966/194512441-0decae3a-89d2-48a7-90ef-f7289102302c.png)

Expected 
![Screenshot from 2022-10-07 14-14-11](https://user-images.githubusercontent.com/40688966/194512549-684840c3-6b61-4194-87ba-791e03de8344.png)

Another concern is, if date-time field is populated in the correct format, is it required to click on Apply button in the calendar (if the calendar issue is fixed)?
Can you please help me with the issues?

**Comment by mikhail-vl** [comment]
@Castlesai, I am sorry for the delayed response.

  I reproduced the issue and will work on a fix.
  Apply should not be required if the DateTime is parsed correctly.

**Comment by Castlesai** [comment]
Thanks, @mikhail-vl  for responding

**Comment by Castlesai** [comment]
Hello @mikhail-vl, can you please give me suggestions to fix this issue?

**Comment by mikhail-vl** [comment]
@Castlesai Issue was resolved and will be a part of today's release.

  Please let me know if there is anything else.
